name: "redis"
description: "stop, clean and start redis in order"
inputs:
    stop:
        description: "whether to stop"
        required: true
    clean:
        description: "whether to clean"
        required: true
    start:
        description: "whether to start"
        required: true
    ports:
        description: "ports to run on"
        required: false
        default: "6379"

runs:
    using: "composite"
    steps:
        - if: fromJSON(inputs.stop) || fromJSON(inputs.clean)
          name: unimplemented
          shell: bash
          run: exit 1

        - if: fromJSON(inputs.start)
          name: Create redis Work Directory
          shell: bash
          working-directory: ${{ github.action_path }}
          run: |
              for port in ${{ inputs.ports }}; do
                mkdir -p $port
              done

        - if: fromJSON(inputs.start)
          name: Start redis
          shell: bash
          working-directory: ${{ github.action_path }}
          run: |
              pwd
              for port in ${{ inputs.ports }}; do
                mkdir -p $port
                redis-server --port $port --dir $port --daemonize yes --pidfile $port/redis.pid || echo "Failed to start Redis on port $port"
                sleep 2
                echo "Redis process status for port $port:"
                ps aux | grep redis-server | grep $port
                echo "Contents of $port directory:"
                ls $port
                echo ls $port
                cat $port/redis.log 2>/dev/null || echo "No log file found"
              done
