name: "dependence-setup"
description: "environment dependence setup"
inputs:
    python-version:
        description: "python version"
        required: false
        default: 3.7
    java:
        description: "java version"
        required: false
        default: 8
    os:
        description: "running environment"
        required: false
        default: ubuntu-latest
runs:
    using: "composite"
    steps:
        - name: Set up Python ${{ inputs.python-version }}
          uses: actions/setup-python@v3
          with:
              python-version: ${{ inputs.python-version }}

        - name: Install Python dependencies
          shell: bash
          run: |
              python -m pip install --upgrade pip
              if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "macOS" ]]; then
                pip install pemja==0.3.0 pandas numpy
              else
                pip install pandas numpy
                "${GITHUB_WORKSPACE}/.github/scripts/pemja/pemja.sh"
              fi

        - name: Set up JDK ${{ inputs.java }}
          uses: actions/setup-java@v1
          with:
              java-version: ${{ inputs.java }}

        - name: Install Pemja On Windows
          shell: bash
          run: |
              "${GITHUB_WORKSPACE}/.github/scripts/pemja/pemja.sh"

#           mvn install:install-file -Dfile=local-dependencies/maven/pemja/pemja-0.5-SNAPSHOT.jar -DgroupId=com.alibaba -DartifactId=pemja -Dversion=0.5-SNAPSHOT -Dpackaging=jar

