name: "dependence-setup"
description: "environment dependence setup"
inputs:
    python-version:
        description: "python version"
        required: false
        default: 3.9
    java:
        description: "java version"
        required: false
        default: 8
    os:
        description: "running environment"
        required: false
        default: ubuntu-latest
    scope:
        description: "partial dependency required"
        required: false
        default: all
        # all: setup all

runs:
    using: "composite"
    steps:
        - name: Set up Docker Buildx
          uses: crazy-max/ghaction-setup-docker@v3

        # need to set up timezone and enlarge JVM heap size manually on windows
        - if: runner.os == 'Windows'
          name: Set Dynamic Timezone
          shell: cmd
          run: |
              tzutil /s "China Standard Time"
              echo "JAVA_OPTS=-Xmx4g -Xms2g" >> %GITHUB_ENV%

        - if: runner.os == 'Windows'
          uses: azure/mysql@v1
          with:
            server-name: REPLACE_THIS_WITH_YOUR_MYSQL_SERVER_NAME
            username: admin@REPLACE_THIS_WITH_YOUR_MYSQL_SERVER_NAME
            password: ${{ secrets.AZURE_MYSQL_PASSWORD }}
            # This is optional, you want to connect directly
            database: REPLACE_WITH_DATABASE_NAME
            sql-file: './sqlFile.sql'

        - if: inputs.scope=='all'
          name: Set up Python ${{ inputs.python-version }}
          uses: actions/setup-python@v3
          with:
              python-version: ${{ inputs.python-version }}

        - if: inputs.scope=='all'
          name: Install Python dependencies
          shell: bash
          run: |
              python -m pip install --upgrade pip
              pip install pandas numpy pemjax==0.1.0

        - name: Set up JDK ${{ inputs.java }}
          uses: actions/setup-java@v1
          with:
              java-version: ${{ inputs.java }}
