name: "dependence-setup"
description: "environment dependence setup"
inputs:
    python-version:
        description: "python version"
        required: false
        default: 3.9
    java:
        description: "java version"
        required: false
        default: 8
    os:
        description: "running environment"
        required: false
        default: ubuntu-latest
    scope:
        description: "partial dependency required"
        required: false
        default: all
        # all: setup all

runs:
    using: "composite"
    steps:
        - name: Set up Docker Buildx
          uses: crazy-max/ghaction-setup-docker@v3

        # need to set up timezone and enlarge JVM heap size manually on windows
        - if: runner.os == 'Windows'
          name: Set Dynamic Timezone
          shell: cmd
          run: |
              tzutil /s "China Standard Time"
              echo "JAVA_OPTS=-Xmx4g -Xms2g" >> %GITHUB_ENV%

        - if: runner.os == 'macOS'
          name: Install Docker on MacOS
          shell: bash
          run: |
              brew install docker colima
              colima start
              docker --version

        - if: inputs.scope=='all'
          name: Set up Python ${{ inputs.python-version }}
          uses: actions/setup-python@v5
          with:
              python-version: ${{ inputs.python-version }}
              cache: "pip" # caching pip dependencies

        - if: inputs.scope=='all'
          name: Install Python dependencies
          shell: bash
          run: |
              python -m pip install --upgrade pip
              pip install pandas numpy pemjax==0.1.0 thrift

        - name: Set up JDK ${{ inputs.java }}
          uses: actions/setup-java@v4
          with:
              java-version: ${{ inputs.java }}
              distribution: "temurin"
              cache: "maven"
