name: "dependence-setup"
description: "environment dependence setup"
inputs:
    python-version:
        description: "python version"
        required: false
        default: 3.9
    java:
        description: "java version"
        required: false
        default: 8
    os:
        description: "running environment"
        required: false
        default: ubuntu-latest
    scope:
        description: "partial dependency required"
        required: false
        default: all
        # all: setup all
    docker-required:
        description: "is docker needed in this test"
        required: false
        default: "false"

runs:
    using: "composite"
    steps:
        # need to set up timezone and enlarge JVM heap size manually on windows
        - if: runner.os == 'Windows'
          name: Set Dynamic Timezone
          shell: cmd
          run: |
              tzutil /s "China Standard Time"
              echo "JAVA_OPTS=-Xmx4g -Xms2g" >> %GITHUB_ENV%

        - if: runner.os == 'macOS' &&  inputs.docker-required=='true'
          name: Install Docker on MacOS
          shell: bash
          run: |
              brew update
              brew install docker
              brew install colima
              sudo curl -L -o /opt/homebrew/Cellar/lima/0.22.0/bin/limactl https://github.com/mikekazakov/lima-nohvf/raw/master/limactl && sudo chmod +x /opt/homebrew/Cellar/lima/0.22.0/bin/limactl
              colima start --network-address --arch arm64 --vm-type=qemu
              docker --version

        - if: inputs.scope=='all'
          name: Set up Python ${{ inputs.python-version }}
          uses: actions/setup-python@v5
          with:
              python-version: ${{ inputs.python-version }}
              cache: "pip" # caching pip dependencies

        - if: inputs.scope=='all'
          name: Install Python dependencies
          shell: bash
          run: |
              python -m pip install --upgrade pip
              pip install pandas numpy pemjax==0.1.0 thrift fastparquet tqdm requests

        - name: Set up JDK ${{ inputs.java }}
          uses: actions/setup-java@v4
          with:
              java-version: ${{ inputs.java }}
              distribution: ${{ runner.os == 'macOS' && matrix.java == '8' && 'liberica' || 'temurin' }}
              cache: "maven"

        - name: Get project info
          id: project
          uses: ./.github/actions/project

        - name: Set up environment variable
          shell: bash
          run: |
              echo "VERSION=${{ steps.project.outputs.version }}" >> $GITHUB_ENV
