name: "dependence-setup"
description: "environment dependence setup"
inputs:
    python-version:
        description: "python version"
        required: false
        default: 3.9
    java:
        description: "java version"
        required: false
        default: 8
    os:
        description: "running environment"
        required: false
        default: ubuntu-latest
    scope:
        description: "partial dependency required"
        required: false
        default: all
        # all: setup all

runs:
    using: "composite"
    steps:
        # need to set up timezone and enlarge JVM heap size manually on windows
        - if: runner.os == 'Windows'
          name: Set Dynamic Timezone
          shell: cmd
          run: |
              tzutil /s "China Standard Time"
              echo "JAVA_OPTS=-Xmx4g -Xms2g" >> %GITHUB_ENV%

        - if: inputs.scope=='all'
          name: Set up Python ${{ inputs.python-version }}
          uses: actions/setup-python@v3
          with:
              python-version: ${{ inputs.python-version }}

        - if: inputs.scope=='all'
          name: Install Python dependencies
          shell: bash
          run: |
              python -m pip install --upgrade pip
              pip install pandas numpy

        - name: Set up JDK ${{ inputs.java }}
          uses: actions/setup-java@v1
          with:
              java-version: ${{ inputs.java }}

        - if: inputs.scope=='all'
          name: Install Pemja Locally
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Windows" ]; then
                pip install https://iginx-thu.github.io/pemja/dist/pemja-0.5.dev0-cp39-cp39-win_amd64.whl            
              else
                pip install https://iginx-thu.github.io/pemja/dist/pemja-0.5.dev0.tar.gz   
              fi
