name: "Database Ports Mapper"
description: "Map database name to corresponding ports"
inputs:
    DB-name:
        description: "Name of the database to get ports for"
        required: true

outputs:
    port1:
        description: "port1"
        value: ${{ steps.get-ports.outputs.port1 }}
    port2:
        description: "port2"
        value: ${{ steps.get-ports.outputs.port2 }}
    port3:
        description: "port3"
        value: ${{ steps.get-ports.outputs.port3 }}

runs:
    using: "composite"
    steps:
        - id: get-ports
          shell: bash
          run: |
              case "${{ inputs.DB-name }}" in
                "InfluxDB")
                  echo "port1=8086" >> $GITHUB_OUTPUT
                  echo "port2=8087" >> $GITHUB_OUTPUT
                  echo "port3=8088" >> $GITHUB_OUTPUT
                  ;;
                "IoTDB12")
                  echo "port1=6667" >> $GITHUB_OUTPUT
                  echo "port2=6668" >> $GITHUB_OUTPUT
                  echo "port3=6669" >> $GITHUB_OUTPUT
                  ;;
                "FileSystem")
                  echo "port1=6667" >> $GITHUB_OUTPUT
                  echo "port2=6668" >> $GITHUB_OUTPUT
                  echo "port3=6669" >> $GITHUB_OUTPUT
                  ;;
                "MySQL")
                  echo "port1=3306" >> $GITHUB_OUTPUT
                  echo "port2=3307" >> $GITHUB_OUTPUT
                  echo "port3=3308" >> $GITHUB_OUTPUT
                  ;;
                "PostgreSQL")
                  echo "port1=5432" >> $GITHUB_OUTPUT
                  echo "port2=5433" >> $GITHUB_OUTPUT
                  echo "port3=5434" >> $GITHUB_OUTPUT
                  ;;
                "MongoDB")
                  echo "port1=27017" >> $GITHUB_OUTPUT
                  echo "port2=27018" >> $GITHUB_OUTPUT
                  echo "port3=27019" >> $GITHUB_OUTPUT
                  ;;
                "Redis")
                  echo "port1=6379" >> $GITHUB_OUTPUT
                  echo "port2=6380" >> $GITHUB_OUTPUT
                  echo "port3=6381" >> $GITHUB_OUTPUT
                  ;;
                *)
                  echo "port1=0" >> $GITHUB_OUTPUT
                  echo "port2=0" >> $GITHUB_OUTPUT
                  echo "port3=0" >> $GITHUB_OUTPUT
                  ;;
              esac
