name: "mongodb"
description: "stop, clean and start mongodb in order"
inputs:
    stop:
        description: "whether to stop"
        required: true
    clean:
        description: "whether to clean"
        required: true
    start:
        description: "whether to start"
        required: true
    ports:
        description: "ports to run on"
        required: false
        default: "27017"

runs:
    using: "composite"
    steps:
        - if: fromJSON(inputs.stop) || fromJSON(inputs.clean)
          name: unimplemented
          shell: bash
          run: exit 1

        - if: fromJSON(inputs.start)
          name: Create Mongodb Work Directory
          shell: bash
          working-directory: ${{ github.action_path }}
          run: |
              for port in ${{ inputs.ports }}; do
                mkdir -p $port
              done

        - if: fromJSON(inputs.start)
          name: Start Mongodb
          shell: bash
          working-directory: ${{ github.action_path }}
          run: |
              for port in ${{ inputs.ports }}; do
                nohup mongod --port $port --dbpath $port --logpath $port/mongodb.log > /dev/null 2>&1 &
                echo $! > $port/mongodb.pid
              done
