name: "oracle"
description: "setup oracle"
inputs:
    version:
        description: "oracle version"
        required: false
        default: "23"

runs:
    using: "composite"
    steps:
        - name: Setup Docker
          uses: ./.github/actions/setup/docker

        - if: runner.os == 'Linux' || runner.os == 'macOS'
          name: Download Oracle Database Docker image
          shell: bash
          run: |
              docker --version
              docker pull container-registry.oracle.com/database/free:23.5.0.0-lite

        - if: runner.os == 'Windows'
          name: Download Oracle Database Docker image
          shell: wsl-bash {0}
          run: |
              docker --version
              docker pull container-registry.oracle.com/database/free:23.5.0.0-lite
