name: "edit"
description: "use sed to edit files in different platforms"
inputs:
  paths:
    description: "file paths delimited by newline and space"
    required: true
  statements:
    description: "sed statements delimited by newline"
    required: true

runs:
    using: "composite"
    steps:
        - name: "edit"
          shell: bash
          run: |
            set -e
            paths=$(echo "${{ inputs.paths }}" | tr '\n' ' ')
            SEDI="sed -i"
            if [ "$RUNNER_OS" == "macOS" ]; then
              SEDI="sed -i ''"
            fi
            ${SEDI} -e "${{ inputs.statements }}" $paths
                

