name: "zookeeper-runner"
description: "zookeeper runner"
inputs:
    os:
        description: "zookeeper runner environment"
        required: false
        default: ubuntu-latest
    if-stop:
        description: "to stop the zookeeper"
        required: false
        default: "false"
    if-rerun:
        description: "to rerun the zookeeper"
        required: false
        default: "false"
    port:
      description: "zk port"
      required: false
      default: "2181"
runs:
    using: "composite" # Mandatory parameter
    steps:
        - if: inputs.if-stop=='false' && inputs.if-rerun=='false'
          name: First Run ZooKeeper | Setup
          uses: ./.github/actions/setup/zookeeper
          with:
              port: ${{ inputs.port }}

        - if: inputs.if-stop=='false' && inputs.if-rerun=='false'
          name: First Run ZooKeeper
          uses: ./.github/actions/service/zookeeper
          with:
              stop: false
              clean: false
              start: true
              port: ${{ inputs.port }}

        - if: inputs.if-rerun=='true'
          name: ReRun ZooKeeper
          uses: ./.github/actions/service/zookeeper
          with:
              stop: false
              clean: false
              start: true
              port: ${{ inputs.port }}

        - if: inputs.if-stop=='true'
          name: Stop ZooKeeper
          uses: ./.github/actions/service/zookeeper
          with:
              stop: true
              clean: true
              start: false
              port: ${{ inputs.port }}
