name: "conf-writer"
description: "use conf-writer to change the target/conf after IGinX was installed"
inputs:
    if-CapExp:
        description: "if you need capacity expansion"
        required: false
        default: "false"
    DB-name:
        description: "DB name"
        required: false
        default: IoTDB12
    Test-Way:
        description: "the way to test"
        required: false
        default: clearData
    Read-Only:
        description: "make the storage engine read-only"
        required: false
        default: "false"
    Has-Data:
        description: "does the storage engine has data"
        required: false
        default: "false"
    Push-Down:
        description: "make the IGinX push down filter"
        required: false
        default: "false"
    Metadata:
        description: "which metadata service to use"
        required: false
        default: zookeeper
    Root-Dir-Path:
        description: "the path of IGinX root directory"
        required: false
        default: "."
    zookeeper-port:
        description: "zookeeper service port"
        required: false
        default: "2181"
    Close-Optimizer:
        description: "close all optimizer"
        required: false
        default: "false"

runs:
    using: "composite" # Mandatory parameter
    steps:
        - id: project
          uses: ./.github/actions/project

        - name: Set Test Environment
          shell: bash
          run: |
              echo "${{ inputs.DB-name }}" > ${{ inputs.Root-Dir-Path }}/test/src/test/resources/DBName.txt
              echo "${{ inputs.if-CapExp }}" > ${{ inputs.Root-Dir-Path }}/test/src/test/resources/isScaling.txt
              echo "${{ inputs.Test-Way }}" > ${{ inputs.Root-Dir-Path }}/test/src/test/resources/dbce-test-way.txt

        - name: Change Zookeeper Port
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/zookeeperConnectionString=127.0.0.1:[0-9]*/zookeeperConnectionString=127.0.0.1:${{ inputs.zookeeper-port }}/g

        - name: Change UDF conf
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/needInitBasicUDFFunctions=false/needInitBasicUDFFunctions=true/g

        - name: Change Python CMD
          if: runner.os == 'Windows'
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/pythonCMD=python3/pythonCMD=python/g

        - if: inputs.Close-Optimizer=='true'
          name: Close All Optimizer
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: |
                  s/Rule=on/Rule=off/g
                  s/enablePushDown=true/enablePushDown=false/g
                  s/ColumnPruningRule=off/ColumnPruningRule=on/g

        - if: inputs.Set-Key-Range-Test-Policy=='true'
          name: Change KeyRangeTestPolicy
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/policyClassName=.*$/policyClassName=cn.edu.tsinghua.iginx.policy.test.KeyRangeTestPolicy/g

        - name: Change Log Conf
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/logger.iginx.level=.*$/logger.iginx.level=debug/g

        - name: Change File Permission
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/file-permission.properties
              statements: |
                  s/^default.transformerRule.include=.*$/default.transformerRule.include=glob:**.denied/g
                  s/^default.transformerRule.write=.*$/default.transformerRule.write=false/g

        - if: inputs.Metadata=='etcd'
          name: Change Metadata to ETCD
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: |
                  s/^metaStorage=.*$/metaStorage=etcd/g
                  s/^zookeeperConnectionString=/#zookeeperConnectionString=/g
                  s/^#etcdEndpoints=/etcdEndpoints=/g

        - name: Hidden All IGinX StorageEngineList
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/^storageEngineList=/#storageEngineList=/g

        - if: inputs.DB-name=='InfluxDB'
          name: Change InfluxDB Config
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: |
                  s/your-token/testToken/g
                  s/your-organization/testOrg/g
                  s/#storageEngineList=127.0.0.1#8086#influxdb/storageEngineList=127.0.0.1#8086#influxdb/g

        - if: inputs.DB-name=='IoTDB12'
          name: Change IoTDB12 Config
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/#storageEngineList=127.0.0.1#6667#iotdb12/storageEngineList=127.0.0.1#6667#iotdb12/g

        - if: inputs.DB-name=='Mix-IoTDB12-InfluxDB'
          name: Change Mix-IoTDB12-InfluxDB Config
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: $astorageEngineList=127.0.0.1#6667#iotdb12#username=root#password=root#sessionPoolSize=50#has_data=false#is_read_only=false,127.0.0.1#8086#influxdb#url=http://localhost:8086/#token=testToken#organization=testOrg#has_data=false

        - if: inputs.DB-name=='MongoDB'
          name: Change MongoDB Config
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/^#storageEngineList=127.0.0.1#27017/storageEngineList=127.0.0.1#27017/g

        - if: inputs.DB-name=='Redis'
          name: Change Redis Config
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/^#storageEngineList=127.0.0.1#6379/storageEngineList=127.0.0.1#6379/g

        - if: inputs.DB-name=='PostgreSQL'
          name: Change PostgreSQL Config
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/^#storageEngineList=127.0.0.1#5432#relational#engine=postgresql/storageEngineList=127.0.0.1#5432#relational#engine=postgresql/g

        - if: inputs.DB-name == 'MySQL'
          name: Change MySQL Config
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s|^#storageEngineList=127.0.0.1#3306#relational#engine=mysql.*$|storageEngineList=127.0.0.1#3306#relational#engine=mysql#username=root#has_data=false|g

        - if: inputs.DB-name == 'Oracle'
          name: Modify IGinX Config
          uses: ./.github/actions/edit
          with:
            paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
            statements: s/^#storageEngineList=127.0.0.1#1521#relational#engine=oracle#username=system#password=Oracle123#has_data=false/storageEngineList=127.0.0.1#1521#relational#engine=oracle#username=system#password=Oracle123#has_data=false/g

        - if: inputs.DB-name == 'FileSystem'
          name: Modify IGinX Config
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: |
                  s/^#storageEngineList=127.0.0.1#[0-9]*#filesystem/storageEngineList=127.0.0.1#6668#filesystem/g
                  s|dir=[^#]*|dir=${{ steps.project.outputs.workspace }}/test/iginx_mn|g
                  s|dummy_dir=[^#]*|dummy_dir=${{ steps.project.outputs.workspace }}/test/mn|g
                  s/data.config.write.buffer.size=[0-9]*/data.config.write.buffer.size=1048576/g
                  s/dummy.struct=[^#]*/dummy.struct=LegacyParquet/g
                  s/chunk_size_in_bytes=[0-9]*/chunk_size_in_bytes=8/g
                  s/write.buffer.size=[0-9]*/write.buffer.size=1048576/g
                  s/client.connectPool.maxTotal=[0-9]*/client.connectPool.maxTotal=2/g

        - name: Set Read-Only
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/is_read_only=[^#]*/is_read_only=${{ inputs.Read-Only }}/g

        - name: Set Has-Data
          uses: ./.github/actions/edit
          with:
              paths: ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
              statements: s/has_data=[^#]*/has_data=${{ inputs.Has-Data }}/g

        - name: Show Config
          shell: bash
          run: cat ${{ inputs.Root-Dir-Path }}/core/target/iginx-core-*/conf/config.properties
