name: "conf-writer"
description: "use conf-writer to change the target/conf after IGinX was installed"
inputs:
    if-CapExp:
        description: "if you need capacity expansion"
        required: false
        default: "false"
    DB-name:
        description: "DB name"
        required: false
        default: IoTDB12
    Test-Way:
        description: "the way to test"
        required: false
        default: clearData
    Read-Only:
        description: "make the storage engine read-only"
        required: false
        default: "false"
    Push-Down:
        description: "make the IGinX push down filter"
        required: false
        default: "false"

runs:
    using: "composite" # Mandatory parameter
    steps:
        - if: inputs.DB-name=='FileSystem' || inputs.DB-name=='Parquet'
          name: save config for FileSystem and Parquet
          shell: bash
          run: |
              cp -f "${GITHUB_WORKSPACE}/conf/config.properties" "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties"

        - name: Set if-CapExp
          shell: bash
          run: |
              echo "${{ inputs.if-CapExp }}" > ${GITHUB_WORKSPACE}/test/src/test/resources/isScaling.txt

        - if: inputs.if-CapExp=='true'
          name: Change has_data
          shell: bash
          run: |
              if [[ "${{ inputs.Test-Way }}" == "oriHasDataExpHasData" || "${{ inputs.Test-Way }}" == "oriHasDataExpNoData" ]]; then
                if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "Windows" ]]; then
                  sed -i "s/has_data=false/has_data=true/g" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                elif [ "$RUNNER_OS" == "macOS" ]; then
                  sed -i "" "s/has_data=false/has_data=true/" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                fi
              elif [[ "${{ inputs.Test-Way }}" == "oriNoDataExpHasData" || "${{ inputs.Test-Way }}" == "oriNoDataExpNoData" ]]; then
                if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "Windows" ]]; then
                  sed -i "s/has_data=true/has_data=false/g" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                elif [ "$RUNNER_OS" == "macOS" ]; then
                  sed -i "" "s/has_data=true/has_data=false/" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                fi
              fi

        - name: Set DB-name
          shell: bash
          run: |
              echo "${{ inputs.DB-name }}" > ${GITHUB_WORKSPACE}/test/src/test/resources/DBName.txt

        - name: Change UDF conf
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                sudo sed -i 's/needInitBasicUDFFunctions=false/needInitBasicUDFFunctions=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "Windows" ]; then
                sed -i 's/needInitBasicUDFFunctions=false/needInitBasicUDFFunctions=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
                sed -i 's/pythonCMD=python3/pythonCMD=python/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "macOS" ]; then
                sudo sed -i '' 's/needInitBasicUDFFunctions=false/needInitBasicUDFFunctions=true/' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.Read-Only=='true'
          name: Change is_read_only
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                sudo sed -i 's/is_read_only=false/is_read_only=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "Windows" ]; then
                sed -i 's/is_read_only=false/is_read_only=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "macOS" ]; then
                sudo sed -i '' 's/is_read_only=false/is_read_only=true/' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi
        - if: inputs.Push-Down=='true'
          name: Change push_down
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                sudo sed -i 's/enablePushDown=false/enablePushDown=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
                sed -i 's/queryOptimizer=rbo/queryOptimizer=rbo,filter_push_down/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "Windows" ]; then
                sed -i 's/enablePushDown=false/enablePushDown=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
                sed -i 's/queryOptimizer=rbo/queryOptimizer=rbo,filter_push_down/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "macOS" ]; then
                sudo sed -i '' 's/enablePushDown=false/enablePushDown=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
                sed -i '' 's/queryOptimizer=rbo/queryOptimizer=rbo,filter_push_down/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi
        - if: inputs.Set-Key-Range-Test-Policy=='true'
          name: Change KeyRangeTestPolicy
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo sed -i 's/policyClassName=cn.edu.tsinghua.iginx.policy.naive.NaivePolicy/policyClassName=cn.edu.tsinghua.iginx.policy.test.KeyRangeTestPolicy/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "Windows" ]; then
                sed -i 's/policyClassName=cn.edu.tsinghua.iginx.policy.naive.NaivePolicy/policyClassName=cn.edu.tsinghua.iginx.policy.test.KeyRangeTestPolicy/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "macOS" ]; then
                  sudo sed -i '' 's/policyClassName=cn.edu.tsinghua.iginx.policy.naive.NaivePolicy/policyClassName=cn.edu.tsinghua.iginx.policy.test.KeyRangeTestPolicy/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              else
                  echo "$RUNNER_OS is not supported"
                  exit 1
              fi
        - if: inputs.Set-Filter-Fragment-OFF=='true'
          name: Set FilterFragmentRule OFF
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo sed -i 's/ruleBasedOptimizer=RemoveNotRule=on,FilterFragmentRule=on/ruleBasedOptimizer=RemoveNotRule=on/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "Windows" ]; then
                sed -i 's/ruleBasedOptimizer=RemoveNotRule=on,FilterFragmentRule=on/ruleBasedOptimizer=RemoveNotRule=on/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "macOS" ]; then
                  sudo sed -i '' 's/ruleBasedOptimizer=RemoveNotRule=on,FilterFragmentRule=on/ruleBasedOptimizer=RemoveNotRule=on/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              else
                  echo "$RUNNER_OS is not supported"
                  exit 1
              fi
