name: "conf-writer"
description: "use conf-writer to change the target/conf after IGinX was installed"
inputs:
    confFile:
        description: "the conf that you want to write"
        required: false
        default: "Conf"
    if-CapExp:
        description: "if you need capacity expansion"
        required: false
        default: "false"
    Test-Way:
        description: "the way to imp"
        required: false
        default: clearData
    DB-name:
        description: "IoTDB version"
        required: false
        default: iotdb12

runs:
    using: "composite" # Mandatory parameter
    steps:
        - if: inputs.if-CapExp=='true'
          name: Change conf/config.properties
          shell: bash
          run: |
              echo "${{inputs.Test-Way}}" > ${GITHUB_WORKSPACE}/test/src/test/java/cn/edu/tsinghua/iginx/integration/ifScaleOutIn.txt
              if [[ "${{inputs.Test-Way}}" == "oriHasDataExpHasData" || "${{inputs.Test-Way}}" == "oriHasDataExpNoData" ]]; then
                if [ "$RUNNER_OS" == "Linux" ]; then
                  sed -i "s/has_data=false/has_data=true/g" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                elif [ "$RUNNER_OS" == "macOS" ]; then
                  sed -i "" "s/has_data=false/has_data=true/" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                fi
              elif [[ "${{inputs.Test-Way}}" == "oriNoDataExpHasData" || "${{inputs.Test-Way}}" == "oriNoDataExpNoData" ]]; then
                if [ "$RUNNER_OS" == "Linux" ]; then
                  sed -i "s/has_data=true/has_data=false/g" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                elif [ "$RUNNER_OS" == "macOS" ]; then
                  sed -i "" "s/has_data=true/has_data=false/" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                fi
              fi

        - if: inputs.confFile=='DBName'
          name: Change conf/config.properties
          shell: bash
          run: |
              echo "${{inputs.DB-name}}" > ${GITHUB_WORKSPACE}/test/src/test/java/cn/edu/tsinghua/iginx/integration/DBConf.txt

        - if: inputs.confFile=='TestModule'
          name: Change conf/config.properties
          shell: bash
          run: |
              echo "${{inputs.Test-Way}}" > ${GITHUB_WORKSPACE}/test/src/test/java/cn/edu/tsinghua/iginx/integration/TestModule.txt

        - if: inputs.confFile=='iginxConf'
          name: Change conf/config.properties
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                sed -i "s/port=6888/port=7888/g" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                sed -i "s/restPort=6666/restPort=7666/g" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
              elif [ "$RUNNER_OS" == "macOS" ]; then
                sed -i "" "s/port=6888/port=7888/" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
                sed -i "" "restPort=6666/restPort=7666/" ${GITHUB_WORKSPACE}/core/target/iginx-core-0.6.0-SNAPSHOT/conf/config.properties
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.confFile=='UDFConf'
          name: Change conf/config.properties
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                sudo sed -i 's/needInitBasicUDFFunctions=false/needInitBasicUDFFunctions=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "macOS" ]; then
                sudo sed -i '' 's/needInitBasicUDFFunctions=false/needInitBasicUDFFunctions=true/' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi
