---
version: "3.9"
services:
  zookeeper:
    container_name: "zookeeper"
    image: "zookeeper:latest"
    networks:
    - "net"
    hostname: "zkServer"
  iginx:
    container_name: "iginx1"
    depends_on:
    - "zookeeper"
    build:
      context: "../../"
      dockerfile: "./docker/oneShot-parquet/Dockerfile"
    command:
    - "/bin/bash"
    - "/root/IGinX/sbin/start_iginx.sh"
    networks:
    - "net"
    ports:
    - "10001:6888"
networks:
  net:
    driver: "bridge"
