name: "Dameng"
description: "setup Dameng"
inputs:
    version:
        description: "Dameng version"
        required: false
        default: "dm8"

runs:
    using: "composite"
    steps:
        - name: Setup Docker
          uses: ./.github/actions/setup/docker

        - if: runner.os == 'Linux'
          name: Install Docker Compose
          shell: bash
          run: |
              DOCKER_COMPOSE_VERSION=v2.30.1
              sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose

        - if: runner.os == 'Linux'
          name: Download Dameng Database Docker image and Load Dameng Database container
          shell: bash
          run: |
              wget https://github.com/IGinX-THU/IGinX-resources/raw/refs/heads/main/resources/dm8_20241022_x86_rh6_64_single.tar
              docker load -i dm8_20241022_x86_rh6_64_single.tar

        - if: runner.os == 'Windows'
          name: Download Dameng Database Docker image and Load Dameng Database container
          shell: wsl-bash {0}
          run: |
              curl -s -S -L -o dm8_20241022_x86_rh6_64_single.tar https://github.com/IGinX-THU/IGinX-resources/raw/refs/heads/main/resources/dm8_20241022_x86_rh6_64_single.tar
              docker load -i dm8_20241022_x86_rh6_64_single.tar
