name: "Dameng"
description: "setup Dameng"
inputs:
    version:
        description: "Dameng version"
        required: false
        default: "dm8"

runs:
    using: "composite"
    steps:
        #        - if: runner.os == 'Windows'
        #          uses: vedantmgoyal9/setup-wsl2@main
        #
        #        - if: runner.os == 'Windows'
        #          run: apt update && apt upgrade -y
        #          shell: wsl-run {0}

        - if: runner.os == 'Linux'
          name: Download Dameng Database Docker image and Load Dameng Database container
          shell: bash
          run: |
              wget https://github.com/IGinX-THU/IGinX-resources/raw/refs/heads/main/resources/dm8_20241022_x86_rh6_64_single.tar
              docker load -i dm8_20241022_x86_rh6_64_single.tar

        #        - if: runner.os == 'Windows'
        #          name: Install Docker
        #          shell: wsl-run {0}
        #          run: |
        #              sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
        #              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        #              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        #              sudo apt update
        #              sudo apt install docker-ce docker-ce-cli containerd.io -y
        #              sudo service docker start

        - if: runner.os == 'Windows'
          name: Download Dameng Database Docker image and Load Dameng Database container
          shell: wsl-run {0}
          run: |
              curl -s -S -L -o dm8_20241022_x86_rh6_64_single.tar https://github.com/IGinX-THU/IGinX-resources/raw/refs/heads/main/resources/dm8_20241022_x86_rh6_64_single.tar
              docker load -i dm8_20241022_x86_rh6_64_single.tar
