name: "docker-compose-setup"
description: "environment docker-compose setup"

runs:
    using: "composite"
    steps:
        - if: runner.os == 'macOS'
          name: Install Docker on MacOS
          shell: bash
          run: |
              brew update
              docker --version
              brew install docker-compose
              docker-compose --version

        - if: runner.os == 'Windows'
          name: Install Docker Compose on Windows
          shell: pwsh
          run: |
              $ErrorActionPreference = "Stop"
              $dockerComposeVersion = "v2.30.1"
              $dockerComposePath = "${{ github.workspace }}\docker-compose.exe"

              # 下载 Docker Compose
              Invoke-WebRequest -Uri "https://github.com/docker/compose/releases/download/$dockerComposeVersion/docker-compose-Windows-x86_64.exe" -OutFile $dockerComposePath
              $dockerComposeDir = [System.IO.Path]::GetDirectoryName($dockerComposePath)
              [System.Environment]::SetEnvironmentVariable("Path", "$env:Path;$dockerComposeDir", [System.EnvironmentVariableTarget]::Machine)
              $env:Path += ";$dockerComposeDir"
              docker --version
              docker-compose --version

        - if: runner.os == 'Linux'
          name: Install Docker Compose
          shell: bash
          run: |
              DOCKER_COMPOSE_VERSION=v2.30.1
              sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
