FROM maven:3-amazoncorretto-8 AS builder
COPY . /root/iginx
WORKDIR /root/iginx
RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim
COPY --from=builder /root/iginx/core/target/iginx-core-0.6.0-SNAPSHOT /iginx

EXPOSE 6888
VOLUME /iginx/logs
ENV PATH="/iginx/sbin/:${PATH}"
ENTRYPOINT /iginx/sbin/start_iginx.sh > /iginx/logs/iginx.log 2>&1