name: "iginx-runner"
description: "iginx runner"
inputs:
    if-stop:
        description: "to stop the iginx"
        required: false
        default: "false"
    if-test-udf:
        description: "to test UDF path detection"
        required: false
        default: "false"

runs:
    using: "composite" # Mandatory parameter
    steps:
        # TODO: use iginx binaries in assembly rather than core
        - if: inputs.if-test-udf=='true'
          name: Test UDF Path
          shell: bash -el {0}
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                sudo sed -i 's/needInitBasicUDFFunctions=false/needInitBasicUDFFunctions=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "Windows" ]; then
                sed -i 's/needInitBasicUDFFunctions=false/needInitBasicUDFFunctions=true/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
                sed -i 's/pythonCMD=python3/pythonCMD=python/g' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              elif [ "$RUNNER_OS" == "macOS" ]; then
                sudo sed -i '' 's/needInitBasicUDFFunctions=false/needInitBasicUDFFunctions=true/' ${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/conf/config.properties
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi
              chmod +x "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx_udf_path.sh"
              "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx_udf_path.sh" ${VERSION}

        - if: inputs.if-test-udf=='false' && inputs.if-stop=='false'
          name: Start IGinX
          shell: bash -el {0}
          run: |
              which python
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx.sh" 6888 7888
              elif [ "$RUNNER_OS" == "Windows" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx_windows.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx_windows.sh" 6888 7888
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx_macos.sh" 6888 7888
              fi

        - if: inputs.if-test-udf=='false' && inputs.if-stop=='true'
          name: Stop IGinX
          shell: bash
          run: |
              chmod +x "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx_kill.sh"
              "${GITHUB_WORKSPACE}/.github/scripts/iginx/iginx_kill.sh"
