name: "mysql"
description: "setup mysql"

runs:
    using: "composite"
    steps:
        - if: runner.os == 'Linux'
          name: Disable AppArmor Service # for change mysql data dir
          shell: bash
          run: |
              sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
              sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

        - name: install redis with package manager
          uses: ./.github/actions/setup/package
          with:
              brew: mysql@8.0

        - name: Show mysql Version
          shell: bash
          working-directory: ${{ github.action_path }}
          run: mysqld --version
