name: "iotdb12"
description: "setup iotdb12"
inputs:
    version:
        description: "iotdb version"
        required: false
        default: "0.12.6"

runs:
    using: "composite"
    steps:
        - id: base
          name: Initialize Setup Configuration
          uses: ./.github/actions/setup/tool
          with:
              tool: iotdb
              version: ${{ inputs.version }}

        - name: Restore iotdb Cache
          id: restore
          uses: actions/cache/restore@v3
          with:
              path: ${{ steps.base.outputs.cache-path }}
              key: ${{ steps.base.outputs.cache-key }}

        - name: Cache iotdb
          uses: actions/cache@v3
          with:
              path: ${{ steps.base.outputs.cache-path }}
              key: ${{ steps.base.outputs.cache-key }}

        - name: Setup iotdb into Runner Tool Cache
          uses: pbrisbin/setup-tool-action@v2
          with:
              name: iotdb
              version: 0.12.6
              url: "https://github.com/thulab/IginX-benchmarks/raw/main/resources/apache-iotdb-0.12.6-server-bin.zip"
              subdir: "apache-iotdb-0.12.6-server-bin"
              ext: "zip"

        - name: Add iotdb ROOT to ENV
          shell: bash
          working-directory: ${{ steps.base.outputs.tool-path }}
          run: echo "IOTDB_ROOT=$PWD" >> $GITHUB_ENV

        - name: Save iotdb Cache
          if: steps.restore.outputs.cache-hit != 'true'
          uses: actions/cache/save@v3
          with:
              path: ${{ steps.base.outputs.cache-path }}
              key: ${{ steps.base.outputs.cache-key }}

        - name: Setup JRE
          id: setup-jre
          uses: pbrisbin/setup-tool-action@v2
          with:
              name: bellsoft-jre
              version: 8u442+7
              url: "https://download.bell-sw.com/java/{version}/{name}{version}-{os}-{arch}.{ext}"
              subdir: "jre8u442"
              subdir-darwin: "jre8u442.jre"
              os-darwin: macos
              os-win32: windows
              arch-arm64: aarch64
              arch-x64: amd64

        - name: Add JAVA_HOME of Java 8 to IoTDB Scripts
          if: runner.os != 'Windows'
          shell: bash
          working-directory: ${{ steps.base.outputs.tool-path }}
          run: |
              perl -i -pe 'print "JAVA_HOME=${{ steps.setup-jre.outputs.directory }}\n" if $. == 20' sbin/start-server.sh
              perl -i -pe 'print "JAVA_HOME=${{ steps.setup-jre.outputs.directory }}\n" if $. == 20' sbin/start-cli.sh

        - name: Add JAVA_HOME of Java 8 to IoTDB Scripts
          if: runner.os == 'Windows'
          shell: python
          working-directory: ${{ steps.base.outputs.tool-path }}
          run: |
              for file in ["sbin/start-server.bat", "sbin/start-cli.bat"]:
                  with open(file, "r") as f:
                      lines = f.readlines()
                  with open(file, "w") as f:
                      for i, line in enumerate(lines):
                          f.write(line)
                          if i == 19:
                              f.write(r"set JAVA_HOME=${{ steps.setup-jre.outputs.directory }}")
                              f.write("\n")
