name: "project"
description: "use maven to get project information in pom.xml"
inputs:
    workspace:
        description: "file paths delimited by space"
        required: false
        default: ${{ github.workspace }}

outputs:
    version:
        description: "project version"
        value: ${{ steps.info.outputs.version }}
    workspace:
        description: "absolute workspace path"
        value: ${{ steps.workspace.outputs.workspace }}

runs:
    using: "composite"
    steps:
        - name: "information"
          id: info
          shell: bash
          working-directory: ${{ inputs.workspace }}
          run: |
              VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
              echo "version=$VERSION" >> $GITHUB_OUTPUT

        - name: "absolute workspace path"
          id: workspace
          shell: bash
          working-directory: ${{ inputs.workspace }}
          run: |
              # if git bash for windows
              if [ "$RUNNER_OS" == "Windows" ]; then
                ABSOLUTE_WORKSPACE=$(pwd -W)
              else
                ABSOLUTE_WORKSPACE=$(pwd)
              fi
              echo "workspace=$ABSOLUTE_WORKSPACE" >> $GITHUB_OUTPUT
