FROM maven:3-amazoncorretto-8 AS builder
COPY . /root/iginx
WORKDIR /root/iginx
RUN mvn clean package -DskipTests -P-format -e

FROM openjdk:11-jre-slim
COPY --from=builder /root/iginx/core/target/iginx-core-0.8.0-SNAPSHOT /iginx

# ports will be cast in run.bat

VOLUME /iginx/logs
ENV PATH="/iginx/sbin/:${PATH}"
ENTRYPOINT /iginx/sbin/start_iginx.sh > /iginx/logs/iginx.log 2>&1