name: "dm"
description: "setup dm"
inputs:
    version:
        description: "dm version"
        required: false
        default: "dm8"

runs:
    using: "composite"
    steps:
#        - if: runner.os == 'Windows'
#          name: Set up Docker on Windows
#          shell: cmd
#          run: |
#              "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchLinuxEngine

        - if: runner.os == 'macOS'
          name: Set up Docker on macOS
          shell: bash
          run: |
              brew update
              brew install docker

        - name: Pull DM Database Docker image
          run: |
              docker pull sizx/dm8
          shell: bash

        - name: Run DM Database container
          run: |
              docker run -d -p 5236:5236 --name dm8 \
              --restart=always --privileged=true \
              -e PAGE_SIZE=16 \
              -e UNICODE_FLAG=1 \
              -e LENGTH_IN_CHAR=1 \
              -e CASE_SENSITIVE=0 \
              -e SYSDBA_PWD='SYSDBA' \
              -e LD_LIBRARY_PATH=/opt/dmdbms/bin \
              -e INSTANCE_NAME=dm8_instance \
              -v /opt/dm8:/opt/dmdbms/data \
              sizx/dm8:1-2-128-22.08.04-166351-20005-CTM
          shell: bash

        - name: Verify DM Database is running
          run: |
              sleep 10
              docker ps
          shell: bash
