name: "dm"
description: "setup dm"
inputs:
    version:
        description: "dm version"
        required: false
        default: "dm8"

runs:
    using: "composite"
    steps:
        - if: runner.os == 'Linux' || runner.os == 'macOS'
          name: Download and Install dm JDBC Driver
          shell: bash
          run: |
              wget https://download.dameng.com/eco/adapter/resource/jdbc/jdbc-20240918.zip            
              unzip jdbc-20240918.zip
              mvn install:install-file 
              -DgroupId=dm.jdbc \
              -DartifactId=DmJdbcDriver8 \
              -Dversion=1.0 \
              -Dpackaging=jar \ 
              -Dfile=jdbc-20240918/DmJdbcDriver8.jar            

        - if: runner.os == 'Windows'
          name: Download and Install dm JDBC Driver
          shell: wsl
          run: |
              wsl wget https://download.dameng.com/eco/adapter/resource/jdbc/jdbc-20240918.zip            
              wsl unzip jdbc-20240918.zip
              mvn install:install-file 
                -DgroupId=dm.jdbc \
                -DartifactId=DmJdbcDriver8 \
                -Dversion=1.0 \
                -Dpackaging=jar \ 
                -Dfile=jdbc-20240918/DmJdbcDriver8.jar   

        - if: runner.os == 'Linux' || runner.os == 'macOS'
          name: Download dm Database Docker image and Run dm Database container
          shell: bash
          run: |
              wget https://github.com/IGinX-THU/IGinX-resources/raw/refs/heads/main/resources/dm8_20241022_x86_rh6_64_single.tar
              docker load -i dm8_20241022_x86_rh6_64_single.tar
            
        - if: runner.os == 'Windows'
          name: Download dm Database Docker image and Run dm Database container
          shell: wsl
          run: |
              wsl wget https://github.com/IGinX-THU/IGinX-resources/raw/refs/heads/main/resources/dm8_20241022_x86_rh6_64_single.tar
              docker load -i dm8_20241022_x86_rh6_64_single.tar

        - name: Verify DM Database is running
          run: |
              sleep 20
              docker ps
          shell: bash
