name: "dm"
description: "setup dm"
inputs:
    version:
        description: "dm version"
        required: false
        default: "dm8"

runs:
    using: "composite"
    steps:
        #        - if: runner.os == 'Windows'
        #          name: Set up Docker on Windows
        #          shell: cmd
        #          run: |
        #              "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchLinuxEngine

#        - if: runner.os == 'macOS'
#          name: Set up Docker on macOS
#          shell: bash
#          run: |
#              brew update
#              brew install docker

        - name: Download DM Database Docker image and Run DM Database container
          run: |
              wget https://github.com/IGinX-THU/IGinX-resources/raw/refs/heads/main/resources/dm8_20241022_x86_rh6_64_single.tar
              docker load -i dm8_20241022_x86_rh6_64_single.tar
              docker run -d -p 5236:5236 --restart=always --name=dm8_test \
              --privileged=true \
              -e LD_LIBRARY_PATH=/opt/dmdbms/bin \
              -e PAGE_SIZE=16 \
              -e EXTENT_SIZE=32 \
              -e LOG_SIZE=1024 \
              -e UNICODE_FLAG=1  \
              -e INSTANCE_NAME=dm8_test \
              -v /opt/data:/opt/dmdbms/data \
              dm8_single:dm8_20241022_rev244896_x86_rh6_64
          shell: bash

        - name: Verify DM Database is running
          run: |
              sleep 20
              docker ps
          shell: bash
