name: "zookeeper"
description: "stop, clean and start zookeeper in order"
inputs:
    stop:
        description: "whether to stop"
        required: true
    clean:
        description: "whether to clean"
        required: true
    start:
        description: "whether to start"
        required: true

runs:
    using: "composite"
    steps:
        - if: fromJSON(inputs.stop)
          name: Stop zookeeper
          shell: bash
          working-directory: ${{ github.action_path }}
          run: zkServer.sh --config conf stop

        - if: fromJSON(inputs.clean)
          name: Clean zookeeper
          shell: bash
          working-directory: ${{ github.action_path }}
          run: rm -rf data logs

        - if: fromJSON(inputs.start)
          name: Start zookeeper
          shell: bash
          working-directory: ${{ github.action_path }}
          run: zkServer.sh --config conf start
