name: "CapExp-Union-Test"
description: "steps to test the capacity expansion"
inputs:
    DB-name:
        description: "DB name"
        required: false
        default: IoTDB12
    Test-Way:
        description: "the way to test"
        required: false
        default: clearData
    Read-Only:
        description: "make the storage engine read-only"
        required: false
        default: "false"
    metadata:
        description: "which metadata service to use"
        required: false
        default: zookeeper

runs:
    using: "composite" # Mandatory parameter
    steps:
        - name: Clear history data
          uses: ./.github/actions/dbWriter
          with:
              DB-name: ${{ inputs.DB-name }}
              Test-Way: clearHistoryData

        - name: Stop IGinX
          uses: ./.github/actions/iginxRunner
          with:
              if-stop: true

        - name: Stop and clear Metadata
          uses: ./.github/actions/metadataRunner
          with:
              if-stop: true
              metadata: ${{ matrix.metadata }}

        - name: Run Metadata
          uses: ./.github/actions/metadataRunner
          with:
              if-rerun: true
              metadata: ${{ matrix.metadata }}

        - name: Write DB history data
          uses: ./.github/actions/dbWriter
          with:
              DB-name: ${{ inputs.DB-name }}
              Test-Way: ${{ inputs.Test-Way }}

        - name: Change IGinX config
          uses: ./.github/actions/confWriter
          with:
              Test-Way: ${{ inputs.Test-Way }}
              if-CapExp: true
              DB-name: ${{ inputs.DB-name }}
              Read-Only: ${{ inputs.Read-Only }}
              metadata: ${{ matrix.metadata }}

        - name: Start IGinX
          uses: ./.github/actions/iginxRunner
