name: "CapExp-Union-Test"
description: "steps to test the capacity expansion"
inputs:
    version:
        description: "iginx runner version"
        required: false
        default: 0.6.0-SNAPSHOT
    DB-name:
        description: "the db version"
        required: false
        default: iotdb12
    Test-Way:
        description: "the way to test"
        required: false
        default: clearData
runs:
    using: "composite" # Mandatory parameter
    steps:
        - name: Clear history data
          uses: ./.github/actions/dbWriter
          with:
              version: ${{inputs.DB-name}}
              Test-Way: clearHistoryData

        - name: Stop IGinX
          uses: ./.github/actions/iginxRunner
          with:
              version: ${{inputs.version}}
              if-stop: true

        - name: Stop and clear ZooKeeper
          uses: ./.github/actions/zookeeperRunner
          with:
              if-stop: true

        - name: Run ZooKeeper
          uses: ./.github/actions/zookeeperRunner
          with:
              if-rerun: true

        - name: Write DB history data
          uses: ./.github/actions/dbWriter
          with:
              version: ${{inputs.DB-name}}
              Test-Way: ${{inputs.Test-Way}}

        - name: Change IGinX config
          uses: ./.github/actions/confWriter
          with:
              Test-Way: ${{inputs.Test-Way}}
              if-CapExp: true

        - name: Start IGinX
          uses: ./.github/actions/iginxRunner
          with:
              version: ${{inputs.version}}
