name: "set context"
description: "set context"
inputs:
    work-name:
        description: "current work name"
        required: false
        default: client
    shell:
        description: "start shell"
        required: false
        default: client
    DB-name:
        description: "DB name"
        required: false
        default: IoTDB12
    metadata:
        description: "which metadata service to use"
        required: false
        default: zookeeper

runs:
    using: "composite" # Mandatory parameter
    steps:
        - if: inputs.work-name=='stop-iginx-meta' || inputs.work-name=='restart-iginx-meta'
          name: Stop IGinX
          uses: ./.github/actions/iginxRunner
          with:
              if-stop: true

        - if: inputs.work-name=='stop-iginx-meta' || inputs.work-name=='restart-iginx-meta'
          name: Stop and clear Metadata Service
          uses: ./.github/actions/metadataRunner
          with:
              if-stop: true
              metadata: ${{ inputs.metadata }}

        - if: inputs.work-name=='start-iginx-meta' || inputs.work-name=='restart-iginx-meta'
          name: Run Metadata Service
          uses: ./.github/actions/metadataRunner
          with:
              if-rerun: true
              metadata: ${{ inputs.metadata }}

        - if: inputs.work-name=='start-iginx-meta' || inputs.work-name=='restart-iginx-meta'
          name: Start IGinX
          uses: ./.github/actions/iginxRunner

        - if: inputs.shell=='client-before'
          name: Pre Test Client Export File
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_outfile.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_outfile.sh" "${{ inputs.DB-name }}" ${VERSION}
              elif [ "$RUNNER_OS" == "Windows" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_outfile_windows.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_outfile_windows.sh" "${{ inputs.DB-name }}" ${VERSION}
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_outfile_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_outfile_macos.sh" "${{ inputs.DB-name }}" ${VERSION}
              fi

        - if: inputs.shell=='client-after'
          name: Pre Test Client Import File
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_infile.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_infile.sh" ${VERSION}
              elif [ "$RUNNER_OS" == "Windows" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_infile_windows.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_infile_windows.sh" ${VERSION}
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_infile_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_infile_macos.sh" ${VERSION}
              fi
