name: "etcd-runner"
description: "etcd runner"
inputs:
    os:
        description: "etcd runner environment"
        required: false
        default: ubuntu-latest
    if-stop:
        description: "to stop the etcd"
        required: false
        default: "false"
    if-rerun:
        description: "to rerun the etcd"
        required: false
        default: "false"

runs:
    using: "composite" # Mandatory parameter
    steps:
        - if: inputs.if-stop=='false' && inputs.if-rerun=='false'
          name: First Run etcd | Setup
          uses: ./.github/actions/setup/etcd

        - if: inputs.if-stop=='false' && inputs.if-rerun=='false'
          name: First Run etcd | Start
          uses: ./.github/actions/service/etcd
          with:
              stop: false
              clean: false
              start: true

        - if: inputs.if-rerun=='true'
          name: ReRun etcd
          uses: ./.github/actions/service/etcd
          with:
              stop: false
              clean: false
              start: true

        - if: inputs.if-stop=='true'
          name: Stop etcd
          uses: ./.github/actions/service/etcd
          with:
              stop: true
              clean: true
              start: false
