name: "install-package"
description: "Install system packages from brew, apt and choco."

inputs:
    apt:
        description: Packages to install with apt on Linux
        required: false
        default: ""
    brew:
        description: Packages to install with brew on macOS
        required: false
        default: ""
    choco:
        description: Packages to install with choco on Windows
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        - if: runner.os == 'Linux' && inputs.apt != ''
          uses: awalsh128/cache-apt-pkgs-action@v1
          with:
              packages: ${{ inputs.apt }}

        - if: runner.os == 'macOS' && inputs.brew != ''
          id: cache-brew
          name: Restore Brew packages Cache
          uses: actions/cache/restore@v4
          with:
              path: |
                  ~/Library/Caches/Homebrew/downloads
                  ~/Library/Caches/Homebrew/Formula
              key: "brew-${{ inputs.brew }}-${{ runner.os }}-${{ runner.arch }}"

        - if: runner.os == 'macOS' && inputs.brew != ''
          name: Install brew packages
          run: |
              brew update-reset
              echo "${{ inputs.brew }}" | xargs -n 1 brew install
          shell: sh

        - if: runner.os == 'macOS' && inputs.brew != '' && steps.cache-brew.outputs.cache-hit != 'true'
          name: Save Brew packages Cache
          uses: actions/cache/save@v4
          with:
              path: |
                  ~/Library/Caches/Homebrew/downloads
                  ~/Library/Caches/Homebrew/Formula
              key: "brew-${{ inputs.brew }}-${{ runner.os }}-${{ runner.arch }}"

        - if: runner.os == 'Windows' && inputs.choco != ''
          id: cache-choco
          name: Restore Choco packages Cache
          uses: actions/cache/restore@v4
          with:
              path: ~\AppData\Local\Temp\chocolatey
              key: "choco-${{ inputs.choco }}-${{ runner.os }}-${{ runner.arch }}"

        - if: runner.os == 'Windows' && inputs.choco != ''
          name: Install choco packages
          run: choco install -y ${{ inputs.choco }}
          shell: sh

        - if: runner.os == 'Windows' && inputs.choco != '' && steps.cache-choco.outputs.cache-hit != 'true'
          name: Save Choco packages Cache
          uses: actions/cache/save@v4
          with:
              path: ~\AppData\Local\Temp\chocolatey
              key: "choco-${{ inputs.choco }}-${{ runner.os }}-${{ runner.arch }}"
