#FROM maven:3-amazoncorretto-8 AS builder
#COPY . /root/iginx
#WORKDIR /root/iginx
#RUN mvn clean package -pl client -am -Dmaven.test.skip=true -P-format -e

FROM mcr.microsoft.com/windows/servercore:ltsc2022
#COPY --from=builder /root/iginx/client/target/iginx-client-0.6.0-SNAPSHOT/ /iginx_client/
COPY . C:/iginx
WORKDIR C:/iginx
COPY ./target/iginx-client-0.6.0-SNAPSHOT/ C:/iginx_client

# install chocolately package manager
#RUN @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin" -Y
#
#RUN choco install openjdk8 -Y
#RUN refreshenv

# 设置环境变量
USER ContainerAdministrator
ENV JAVA_HOME "C:\jdk\jdk-11.0.2"
RUN setx /M PATH "%JAVA_HOME%\bin;%PATH%"
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
# 下载 JDK
ADD https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip C:/temp/jdk.zip

# 解压 JDK
RUN Expand-Archive -Path C:/temp/jdk.zip -DestinationPath C:/jdk

RUN New-Item -Path 'C:/iginx_client/logs' -ItemType Directory
RUN New-Item -Path 'C:/iginx_client/data' -ItemType Directory
USER ContainerUser

ENTRYPOINT ["cmd", "/c", "ping", "localhost", "-t"]