ARG VERSION=0.6.0-SNAPSHOT
ENV VERSION=${VERSION}

FROM openjdk:11-jre-slim
COPY ./target/iginx-client-${VERSION}/ /iginx_client/

RUN mkdir -p /iginx_client/logs
RUN mkdir -p /iginx_client/data
VOLUME /iginx_client/logs
ENV PATH="/iginx_client/sbin/:${PATH}"
ENTRYPOINT ["tail", "-f", "/dev/null"]