#FROM maven:3-amazoncorretto-8 AS builder
#COPY . /root/iginx
#WORKDIR /root/iginx
#RUN mvn clean package -pl client -am -Dmaven.test.skip=true -P-format -e

FROM jenkins4eval/openjdk:11-jdk-hotspot-windowsservercore-ltsc2019
#COPY --from=builder /root/iginx/client/target/iginx-client-0.6.0-SNAPSHOT/ /iginx_client/
COPY . C:/iginx
WORKDIR C:/iginx
COPY ./target/iginx-client-0.6.0-SNAPSHOT/ C:/iginx_client

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# 下载 JDK
ADD https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip C:/temp/jdk.zip

# 解压 JDK
RUN Expand-Archive -Path C:/temp/jdk.zip -DestinationPath C:/jdk; \
    Remove-Item -Path C:/temp/jdk.zip

# 设置环境变量
ENV JAVA_HOME C:\\jdk\\jdk-11.0.2
ENV PATH ${JAVA_HOME}\\bin:${PATH}

RUN mkdir C:/iginx_client/logs
RUN mkdir C:/iginx_client/data
VOLUME C:/iginx_client/logs
ENTRYPOINT ["cmd", "/c", "ping", "localhost", "-t"]