# Build client package with mvn before building the image
FROM mcr.microsoft.com/windows/servercore:ltsc2022
COPY . C:/iginx
WORKDIR C:/iginx
COPY ./target/iginx-client-0.7.0/ C:/iginx_client

# 设置环境变量
USER ContainerAdministrator
ENV JAVA_HOME "C:\jdk\jdk-11.0.2"
RUN setx /M PATH "%JAVA_HOME%\bin;%PATH%"
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# 下载 JDK
ADD https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip C:/temp/jdk.zip

# 解压 JDK
RUN Expand-Archive -Path C:/temp/jdk.zip -DestinationPath C:/jdk

RUN New-Item -Path 'C:/iginx_client/logs' -ItemType Directory
RUN New-Item -Path 'C:/iginx_client/data' -ItemType Directory

ENTRYPOINT ["cmd", "/c", "ping -t localhost > NUL"]