FROM openjdk:11-jre-slim
COPY ./target/iginx-client-0.9.0-SNAPSHOT/ /iginx_client/

RUN mkdir -p /iginx_client/logs
RUN mkdir -p /iginx_client/data
VOLUME /iginx_client/logs
ENV PATH="/iginx_client/sbin/:${PATH}"
ENTRYPOINT ["tail", "-f", "/dev/null"]