#FROM maven:3-amazoncorretto-8 AS builder
#COPY . /root/iginx
#WORKDIR /root/iginx
#RUN mvn clean package -pl client -am -Dmaven.test.skip=true -P-format -e

FROM mcr.microsoft.com/openjdk/jdk:11-ubuntu
#COPY --from=builder /root/iginx/client/target/iginx-client-0.6.0-SNAPSHOT/ /iginx_client/
COPY . C:/iginx
WORKDIR C:/iginx
COPY ./target/iginx-client-0.6.0-SNAPSHOT/ C:/iginx_client

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN mkdir C:/iginx_client/logs
RUN mkdir C:/iginx_client/data
VOLUME C:/iginx_client/logs
ENTRYPOINT ["cmd", "/c", "ping", "localhost", "-t"]