# Build client package with mvn before building the image
FROM mcr.microsoft.com/windows/servercore:ltsc2022
COPY . C:/iginx
WORKDIR C:/iginx
COPY ./target/iginx-client-0.9.0-SNAPSHOT/ C:/iginx_client

# 设置环境变量
USER ContainerAdministrator
ENV JAVA_HOME "C:\jdk\jdk17.0.14_7"
RUN setx /M PATH "%JAVA_HOME%\bin;%PATH%"
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# 下载 JDK
ADD https://corretto.aws/downloads/resources/17.0.14.7.1/amazon-corretto-17.0.14.7.1-windows-x64-jdk.zip C:/temp/jdk.zip

# 解压 JDK
RUN Expand-Archive -Path C:/temp/jdk.zip -DestinationPath C:/jdk

RUN New-Item -Path 'C:/iginx_client/logs' -ItemType Directory
RUN New-Item -Path 'C:/iginx_client/data' -ItemType Directory

ENTRYPOINT ["cmd", "/c", "ping -t localhost > NUL"]