name: 'iotdb-runner'
description: 'iotdb runner'
inputs:
  version:
    description: 'IoTDB version'
    required: false
    default: iotdb12

runs:
  using: "composite" # Mandatory parameter
  steps:
    - name: Run IoTDB
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/${{inputs.version}}.sh"
          "${GITHUB_WORKSPACE}/.github/${{inputs.version}}.sh"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/${{inputs.version}}_macos.sh"
          "${GITHUB_WORKSPACE}/.github/${{inputs.version}}_macos.sh"
        else
          echo "$RUNNER_OS is not supported"
          exit 1
        fi