name: "etcd"
description: "setup etcd"
inputs:
    version:
        description: "etcd version"
        required: false
        default: "3.5.13"

runs:
    using: "composite"
    steps:
        - id: base
          name: Initialize Setup Configuration
          uses: ./.github/actions/setup/tool
          with:
              tool: etcd
              version: ${{ inputs.version }}

        - name: Restore etcd Cache
          id: restore
          uses: actions/cache/restore@v3
          with:
              path: ${{ steps.base.outputs.cache-path }}
              key: ${{ steps.base.outputs.cache-key }}

        - name: Setup etcd into Runner Tool Cache
          uses: pbrisbin/setup-tool-action@v2
          with:
              name: etcd
              version: ${{ inputs.version }}
              url: "https://github.com/etcd-io/etcd/releases/download/v{version}/{name}-v{version}-{os}-{arch}.{ext}"
              subdir: "{name}-v{version}-{os}-{arch}"
              arch: amd64
              os-win32: windows
              ext-darwin: zip

        - name: Show etcd Version
          shell: bash
          working-directory: ${{ github.action_path }}
          run: etcd -version

        - name: Save etcd Cache
          if: steps.restore.outputs.cache-hit != 'true'
          uses: actions/cache/save@v3
          with:
              path: ${{ steps.base.outputs.cache-path }}
              key: ${{ steps.base.outputs.cache-key }}
