name: 'db-runner'
description: 'db runner'
inputs:
  version:
    description: 'DB name'
    required: false
    default: iotdb12

runs:
  using: "composite" # Mandatory parameter
  steps:
    - if: inputs.version=='InfluxDB'
      name: Run DB
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/influxdb.sh"
          "${GITHUB_WORKSPACE}/.github/influxdb.sh"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
          "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
        else
          echo "$RUNNER_OS is not supported"
          exit 1
        fi

    - if: inputs.version=='IoTDB12'
      name: Run DB
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/iotdb12.sh"
          "${GITHUB_WORKSPACE}/.github/iotdb12.sh"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/iotdb12_macos.sh"
          "${GITHUB_WORKSPACE}/.github/iotdb12_macos.sh"
        else
          echo "$RUNNER_OS is not supported"
          exit 1
        fi

    - if: inputs.version=='Parquet'
      name: Run DB
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/parquet.sh"
          "${GITHUB_WORKSPACE}/.github/parquet.sh"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/parquet_macos.sh"
          "${GITHUB_WORKSPACE}/.github/parquet_macos.sh"
        else
          echo "$RUNNER_OS is not supported"
          exit 1
        fi

    - if: inputs.version=='Mix-IoTDB12-InfluxDB'
      name: Run DB
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/mix_iotdb12_influxdb.sh"
          "${GITHUB_WORKSPACE}/.github/mix_iotdb12_influxdb.sh"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/mix_iotdb12_influxdb_macos.sh"
          "${GITHUB_WORKSPACE}/.github/mix_iotdb12_influxdb_macos.sh"
        else
          echo "$RUNNER_OS is not supported"
          exit 1
        fi