name: "db-runner"
description: "db runner"
inputs:
    DB-name:
        description: "DB name"
        required: false
        default: IoTDB12

runs:
    using: "composite" # Mandatory parameter
    steps:
        - if: inputs.DB-name=='InfluxDB'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/influxdb.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/influxdb.sh" 8088 8087
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/influxdb_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/influxdb_macos.sh" 8088 8087
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='IoTDB12'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/iotdb12.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/iotdb12.sh" 6669 6668 6667
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/iotdb12_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/iotdb12_macos.sh" 6669 6668 6667
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='Parquet'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/parquet.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/parquet.sh"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/parquet_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/parquet_macos.sh"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='MongoDB'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/mongodb.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/mongodb.sh"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/mongodb_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/mongodb_macos.sh"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='Redis'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/redis.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/redis.sh" 6381 6380 6379
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/redis_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/redis_macos.sh" 6381 6380 6379
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='Mix-IoTDB12-InfluxDB'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/mix_iotdb12_influxdb.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/mix_iotdb12_influxdb.sh"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/mix_iotdb12_influxdb_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/mix_iotdb12_influxdb_macos.sh"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='PostgreSQL'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/postgresql.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/postgresql.sh" 5434 5433 5432
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/postgresql_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/postgresql_macos.sh" 5434 5433 5432
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi
