name: "db-runner"
description: "db runner"
inputs:
    DB-name:
        description: "DB name"
        required: false
        default: IoTDB12
    IoTDB12-ports:
        description: "IoTDB12 ports"
        required: false
        default: 6667
    InfluxDB-ports:
        description: "InfluxDB ports"
        required: false
        default: 8086
    MongoDB-ports:
        description: "MongoDB ports"
        required: false
        default: 27017
    MySQL-ports:
        description: "MySQL ports"
        required: false
        default: 3306
    PostgreSQL-ports:
        description: "PostgreSQL ports"
        required: false
        default: 5432
    Redis-ports:
        description: "Redis ports"
        required: false
        default: 6379

runs:
    using: "composite" # Mandatory parameter
    steps:
        - if: inputs.DB-name=='InfluxDB' || inputs.DB-name=='Mix-IoTDB12-InfluxDB'
          name: Setup DB
          uses: ./.github/actions/setup/influxdb

        - if: inputs.DB-name=='InfluxDB' || inputs.DB-name=='Mix-IoTDB12-InfluxDB'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/influxdb.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/influxdb.sh" ${{ inputs.InfluxDB-ports }}
              elif [ "$RUNNER_OS" == "Windows" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/influxdb_windows.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/influxdb_windows.sh" ${{ inputs.InfluxDB-ports }}
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/influxdb_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/influxdb_macos.sh" ${{ inputs.InfluxDB-ports }}
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='IoTDB12' || inputs.DB-name=='Mix-IoTDB12-InfluxDB'
          name: Setup DB
          uses: ./.github/actions/setup/iotdb12

        - if: inputs.DB-name=='IoTDB12' || inputs.DB-name=='Mix-IoTDB12-InfluxDB'
          name: Run DB
          shell: bash
          run: |
              java -version
              which java
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/iotdb12.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/iotdb12.sh" ${{ inputs.IoTDB12-ports }}
              elif [ "$RUNNER_OS" == "Windows" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/iotdb12_windows.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/iotdb12_windows.sh" ${{ inputs.IoTDB12-ports }}
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/iotdb12_macos.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/dataSources/startup/iotdb12_macos.sh" ${{ inputs.IoTDB12-ports }}
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='MongoDB'
          name: Setup DB
          uses: ./.github/actions/setup/mongodb

        - if: inputs.DB-name=='MongoDB'
          name: Run DB
          uses: ./.github/actions/service/mongodb
          with:
              stop: false
              clean: false
              start: true
              ports: ${{ inputs.MongoDB-ports }}

        - if: inputs.DB-name=='Redis'
          name: Setup DB
          uses: ./.github/actions/setup/redis

        - if: inputs.DB-name=='Redis'
          name: Run DB
          uses: ./.github/actions/service/redis
          with:
              stop: false
              clean: false
              start: true
              ports: ${{ inputs.Redis-ports }}

        - if: inputs.DB-name=='PostgreSQL'
          name: Setup DB
          uses: ./.github/actions/setup/postgresql

        - if: inputs.DB-name=='PostgreSQL'
          name: Run DB
          uses: ./.github/actions/service/postgresql
          with:
              stop: false
              clean: false
              start: true
              ports: ${{ inputs.PostgreSQL-ports }}

        - if: inputs.DB-name=='MySQL'
          name: Setup DB
          uses: ./.github/actions/setup/mysql

        - if: inputs.DB-name == 'MySQL'
          name: Start MySQL Service
          uses: ./.github/actions/service/mysql
          with:
              ports: ${{ inputs.MySQL-ports }}
