name: "db-runner"
description: "db runner"
inputs:
    DB-name:
        description: "DB name"
        required: false
        default: IoTDB12
    Port:
        description: "DB port"
        required: false
        default: noport

runs:
    using: "composite" # Mandatory parameter
    steps:
        - if: inputs.DB-name=='InfluxDB'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/influxdb.sh"
                "${GITHUB_WORKSPACE}/.github/influxdb.sh 8087"
                "${GITHUB_WORKSPACE}/.github/influxdb.sh 8086"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
                "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh 8087"
                "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh 8086"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='IoTDB12'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/iotdb12.sh"
                "${GITHUB_WORKSPACE}/.github/iotdb12.sh 6668"
                "${GITHUB_WORKSPACE}/.github/iotdb12.sh 6667"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/iotdb12_macos.sh"
                "${GITHUB_WORKSPACE}/.github/iotdb12_macos.sh 6668"
                "${GITHUB_WORKSPACE}/.github/iotdb12_macos.sh 6667" 
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='Parquet'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/parquet.sh"
                "${GITHUB_WORKSPACE}/.github/parquet.sh 6667"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/parquet_macos.sh"
                "${GITHUB_WORKSPACE}/.github/parquet_macos.sh 6667"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='MongoDB'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/mongodb.sh"
                "${GITHUB_WORKSPACE}/.github/mongodb.sh 27017"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/mongodb_macos.sh"
                "${GITHUB_WORKSPACE}/.github/mongodb_macos.sh 27017"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='FileSystem'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/filesystem.sh"
                "${GITHUB_WORKSPACE}/.github/filesystem.sh ${{ inputs.Port }}"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/filesystem_macos.sh"
                "${GITHUB_WORKSPACE}/.github/filesystem_macos.sh ${{ inputs.Port }}"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='Redis'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/redis.sh"
                "${GITHUB_WORKSPACE}/.github/redis.sh 6380" 
                "${GITHUB_WORKSPACE}/.github/redis.sh 6379"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/redis_macos.sh"
                "${GITHUB_WORKSPACE}/.github/redis_macos.sh 6380"
                "${GITHUB_WORKSPACE}/.github/redis_macos.sh 6379"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='Mix-IoTDB12-InfluxDB'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/mix_iotdb12_influxdb.sh"
                "${GITHUB_WORKSPACE}/.github/mix_iotdb12_influxdb.sh"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/mix_iotdb12_influxdb_macos.sh"
                "${GITHUB_WORKSPACE}/.github/mix_iotdb12_influxdb_macos.sh"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi

        - if: inputs.DB-name=='PostgreSQL'
          name: Run DB
          shell: bash
          run: |
              if [ "$RUNNER_OS" == "Linux" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/postgresql.sh"
                "${GITHUB_WORKSPACE}/.github/postgresql.sh 5434"
                "${GITHUB_WORKSPACE}/.github/postgresql.sh 5432"
              elif [ "$RUNNER_OS" == "macOS" ]; then
                chmod +x "${GITHUB_WORKSPACE}/.github/postgresql_macos.sh"
                "${GITHUB_WORKSPACE}/.github/postgresql_macos.sh 5434"
                "${GITHUB_WORKSPACE}/.github/postgresql_macos.sh 5432"
              else
                echo "$RUNNER_OS is not supported"
                exit 1
              fi
