name: "build-pemja-wheels"
description: "build pemja wheels"
inputs:
  pemja-version:
    description: "version of pemja"
    required: false
    default: "0.1.0"

runs:
  using: "composite"
  steps:
    - name: Set Python variables
      shell: bash
      run: |
        echo "PEMJAX_HOME=pemjax-${{ inputs.pemja-version }}-${{ runner.os}}" >> $GITHUB_ENV

    - name: Restore wheel
      id: restore-wheel
      uses: actions/cache/restore@v3
      with:
        path: $PEMJAX_HOME/pemjax-${{ inputs.pemja-version }}/dist
        key: ${{ runner.os }}-pemjax-${{ inputs.pemja-version }}

    - name: Build wheel
      if: steps.restore-wheel.outputs.cache-hit!='true' && runner.os!='Windows'
      shell: bash
      run: |
        curl -O https://bootstrap.pypa.io/get-pip.py
        sudo python3.13t get-pip.py
        sudo python3.13t -m pip install setuptools wheel find-libpython build pandas==2.2.3 numpy
        python3.13t -m pip freeze list

        mkdir -p $PEMJAX_HOME
        tar -xzf dependency/src/main/resources/python/pemjax-${{ inputs.pemja-version }}.tar.gz -C $PEMJAX_HOME
        ls
        cd $PEMJAX_HOME/pemjax-${{ inputs.pemja-version }}

        python3.13t setup.py bdist_wheel

    # pandas 2.2.3 cannot be directly installed on windows yet. use dev wheel file
    - name: Build wheel
      if: steps.restore-wheel.outputs.cache-hit!='true' && runner.os=='Windows'
      shell: bash
      run: |
        curl -O https://bootstrap.pypa.io/get-pip.py
        python3.13t get-pip.py
        python3.13t -m pip install setuptools wheel find-libpython build numpy
        python3.13t -m pip install dependency/src/main/resources/python/pandas*.whl
        python3.13t -m pip freeze list
        
        mkdir -p $PEMJAX_HOME
        tar -xzf dependency/src/main/resources/python/pemjax-${{ inputs.pemja-version }}.tar.gz -C $PEMJAX_HOME
        ls
        cd $PEMJAX_HOME/pemjax-${{ inputs.pemja-version }}
        
        python3.13t setup.py bdist_wheel

    - name: Install pemjax wheel
      if: runner.os!='Windows'
      shell: bash
      run: |
        sudo python3.13t -m pip install $PEMJAX_HOME/pemjax-${{ inputs.pemja-version }}/dist/*.whl --no-clean
        python3.13t -m pip freeze list

    - name: Install pemjax wheel
      if: runner.os=='Windows'
      shell: bash
      run: |
        python3.13t -m pip install $PEMJAX_HOME/pemjax-${{ inputs.pemja-version }}/dist/*.whl --no-clean
        python3.13t -m pip freeze list

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-pemjax-wheel
        path: $PEMJAX_HOME/pemjax-${{ inputs.pemja-version }}/dist/*.whl

    - name: Cache wheel
      id: cache-wheel
      uses: actions/cache/save@v3
      with:
        path: $PEMJAX_HOME/pemjax-${{ inputs.pemja-version }}/dist
        key: ${{ runner.os }}-pemjax-${{ inputs.pemja-version }}