name: activate-conda
description: install conda and create env
inputs:
  conda-version:
    description: "conda version"
    required: false
    default: "24.5.0-0"
  python-version-major:
    description: "python major version"
    required: false
    default: "3"
  python-version-minor:
    description: "python minor version"
    required: false
    default: "12"

runs:
  using: "composite"
  steps:
    - name: Set cache variables
      id: set-cache-var
      shell: bash
      run: |
        version=py${{ inputs.python-version-major }}${{ inputs.python-version-minor }}_${{ inputs.conda-version }}
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "CONDA_INSTALLER_URL=https://repo.anaconda.com/miniconda/Miniconda3-${version}-Windows-x86_64.exe" >> $GITHUB_ENV
          echo "CONDA_INSTALLER_PATH=miniconda.exe" >> $GITHUB_ENV
          echo "CACHE_KEY=conda-windows-${version}" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "CONDA_INSTALLER_URL=https://repo.anaconda.com/miniconda/Miniconda3-${version}-MacOSX-arm64.sh" >> $GITHUB_ENV
          echo "CONDA_INSTALLER_PATH=~/miniconda3/miniconda.sh" >> $GITHUB_ENV
          echo "CACHE_KEY=python-macos-${version}" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "Linux" ]; then
          echo "CONDA_INSTALLER_URL=https://repo.anaconda.com/miniconda/Miniconda3-${version}-Linux-x86_64.sh" >> $GITHUB_ENV
          echo "CONDA_INSTALLER_PATH=~/miniconda3/miniconda.sh" >> $GITHUB_ENV
          echo "CACHE_KEY=python-linux-${version}" >> $GITHUB_ENV
        fi

    - name: Restore Installer
      id: restore-cache-installer
      uses: actions/cache/restore@v3
      with:
        key: ${{ env.CACHE_KEY }}
        path: ${{ env.CONDA_INSTALLER_PATH }}

    - name: Download Conda Installer
      if: steps.restore-cache-installer.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -o $CONDA_INSTALLER_PATH $CONDA_INSTALLER_URL

    - name: Install Conda
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Start-Process -FilePath ".\$CONDA_INSTALLER_PATH" -ArgumentList "/S" -Wait

    - name: Install Conda
      if: runner.os != 'Windows'
      shell: bash
      run: |
        mkdir -p ~/miniconda3
        bash $CONDA_INSTALLER_PATH -b -u -p ~/miniconda3
        source ~/miniconda3/bin/activate
        conda init --all
