name: "db-writer"
description: "db writer"
inputs:
    version:
        description: "DB version"
        required: false
        default: iotdb12
    Test-Way:
        description: "the way to imp"
        required: false
        default: clearData
runs:
    using: "composite" # Mandatory parameter
    steps:
        - name: Write history data
          shell: bash
          run: |
              mvn test -q -Dtest=${{inputs.version}}HistoryDataGenerator#${{inputs.Test-Way}} -DfailIfNoTests=false -P passFormat
