name: "db-writer"
description: "db writer"
inputs:
    DB-name:
        description: "DB name"
        required: false
        default: IoTDB12
    Test-Way:
        description: "the way to imp"
        required: false
        default: clearData
runs:
    using: "composite" # Mandatory parameter
    steps:
        - name: Write history data
          shell: bash
          run: |
              mvn test -Dtest=${{ inputs.DB-name }}HistoryDataGenerator#${{ inputs.Test-Way }} -Dsurefire.failIfNoSpecifiedTests=false -P-format
