name: "db-writer"
description: "db writer"
inputs:
    version:
        description: "DB version"
        required: false
        default: iotdb12
    Test-Way:
        description: "the way to imp"
        required: false
        default: clearData
runs:
    using: "composite" # Mandatory parameter
    steps:
        - if: inputs.version=='IoTDB12'
          name: Write history Data
          shell: bash
          run: |
              mvn test -q -Dtest=IoTDB12HistoryDataGenerator#${{inputs.Test-Way}} -DfailIfNoTests=false

        - if: inputs.version=='InfluxDB'
          name: Write history Data
          shell: bash
          run: |
              mvn test -q -Dtest=InfluxDBHistoryDataGenerator#${{inputs.Test-Way}} -DfailIfNoTests=false
