name: "show DB log"
description: "show DB log"
inputs:
    DB-name:
        description: "DB name"
        required: true
        default: IoTDB12

runs:
    using: "composite"
    steps:
        - if: ${{ inputs.DB-name=='Mix-IoTDB12-InfluxDB' && runner.os == 'Windows' }}
          name: Show DB Log
          shell: bash
          run: |
              "${GITHUB_WORKSPACE}/.github/actions/dbLog/dbLog.sh" IoTDB12
              "${GITHUB_WORKSPACE}/.github/actions/dbLog/dbLog.sh" InfluxDB

        - if: ${{ inputs.DB-name!='Mix-IoTDB12-InfluxDB' && runner.os == 'Windows' }}
          name: Show DB Log
          shell: bash
          run: |
              "${GITHUB_WORKSPACE}/.github/actions/dbLog/dbLog.sh" ${{ inputs.DB-name }}

        - if: ${{ inputs.DB-name == 'VectorDB' && runner.os != 'Windows' }}
          name: Show Milvus Log
          working-directory: ${{ github.workspace }}
          shell: bash
          run: |
              docker compose -f 19530/docker-compose-19530.yml logs | grep -v INFO |grep -v '"info"'
              ls volumes19530
              du -sh volumes19530
              du -sh volumes19530/etcd
              du -sh volumes19530/milvus

        - if: ${{ inputs.DB-name == 'VectorDB' && runner.os == 'Windows' }}
          name: Show Milvus Log on Windows
          working-directory: ${{ github.workspace }}
          shell: wsl-bash {0}
          run: |
              docker compose -f 19530/docker-compose-19530.yml logs | grep -v INFO |grep -v '"info"'
