name: "show DB log"
description: "show DB log"
inputs:
    DB-name:
        description: "DB name"
        required: true
        default: IoTDB12

runs:
    using: "composite"
    steps:
        - if: ${{ inputs.DB-name=='Mix-IoTDB12-InfluxDB' && runner.os == 'Windows' }}
          name: Show DB Log
          shell: bash
          run: |
              "./dbLog.sh" IoTDB12
              "./dbLog.sh" InfluxDB

        - if: ${{ inputs.DB-name!='Mix-IoTDB12-InfluxDB' && runner.os == 'Windows' }}
          name: Show DB Log
          shell: bash
          run: |
              "./dbLog.sh" ${{ inputs.list_input }}
