name: Benchmark Tests

on:
    push:
        branches: [feat-benchmark]

env:
    VERSION: 0.6.0-SNAPSHOT
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Benchmark-Test:
        timeout-minutes: 35
        strategy:
            fail-fast: false
            matrix:
                java: [8]
                python-version: ["3.9"]
                os: [ubuntu-latest, macos-latest, windows-latest]
                DB-name:
                    [
                        "IoTDB12",
                        "InfluxDB",
                        "Parquet",
                        "PostgreSQL",
                        "FileSystem",
                        "Redis",
                        "MongoDB",
                    ]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Print DB name
              run: echo ${{ matrix.DB-name }}
