name: Benchmark Tests

on:
    push:
        branches: [feat-benchmark]

env:
    VERSION: 0.6.0-SNAPSHOT
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Benchmark-Test:
        timeout-minutes: 35
        strategy:
            fail-fast: false
            matrix:
                java: [8]
                python-version: ["3.9"]
                os: [ubuntu-latest, macOS-13, windows-latest]
                DB-name:
                    [
                        "IoTDB12",
                        "InfluxDB",
                        "Parquet",
                        "PostgreSQL",
                        "FileSystem",
                        "Redis",
                        "MongoDB",
                    ]
                metadata: [zookeeper]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
            - name: Environment dependence
              uses: ./.github/actions/dependence
              with:
                  python-version: ${{ matrix.python-version }}
                  java: ${{ matrix.java }}

            - name: Run ZooKeeper
              uses: ./.github/actions/zookeeperRunner

            - name: Run DB
              uses: ./.github/actions/dbRunner
              with:
                  DB-name: ${{ matrix.DB-name }}

            - name: Install IGinX with Maven
              shell: bash
              run: |
                  mvn clean package -DskipTests -P-format -q

            - name: Change IGinX config
              uses: ./.github/actions/confWriter
              with:
                  DB-name: ${{ matrix.DB-name }}
                  Set-Filter-Fragment-OFF: "true"

            # start udf path test first to avoid being effected
            - name: Start IGinX
              uses: ./.github/actions/iginxRunner
              with:
                  version: ${VERSION}
                  if-test-udf: "true"

            - name: set client test context
              uses: ./.github/actions/context
              with:
                  work-name: restart-iginx-meta
                  metadata: ${{ matrix.metadata }}

            - name: set client test context
              uses: ./.github/actions/context
              with:
                  DB-name: ${{ matrix.DB-name }}
                  shell: client-before

            - name: Start data cleaning
              shell: bash
              run: |
                  pwd
                  if [ "$RUNNER_OS" == "Windows" ]; then
                    python test/src/test/java/cn/edu/tsinghua/iginx/integration/polybench/DataCleaningRunner.py
                  else
                    python3 test/src/test/java/cn/edu/tsinghua/iginx/integration/polybench/DataCleaningRunner.py
                  fi

            - name: Start sgd test
              shell: bash
              run: |
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/benchmarks/sgd.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/benchmarks/sgd.sh"
