name: "Capacity-Expansion-Test"
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
env:
  VERSION: 0.6.0-SNAPSHOT
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Union-DB-Test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
        DB-name: [ "iotdb12" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Environmet Dependence
        uses: ./.github/actions/dependence
        with:
          python-version: ${{ matrix.python-version }}
          java: ${{ matrix.java }}
      - name: Run ZooKeeper
        uses: ./.github/actions/zookeeperRunner
      - name: Run IoTDB
        uses: ./.github/actions/iotdbRunner
        with:
          version: ${{matrix.DB-name}}

      - name: Change pom
        run: |
          mv test/pom.xml test/pom.xml.backup
          mv test/pom.xml.${{matrix.DB-name}} test/pom.xml
      - name: Install IginX with Maven
        shell: bash
        run: |
          mvn clean package -DskipTests

      - name: Set The DB Name
        uses: ./.github/actions/confWriter
        with:
          confFile: DBName
          DB-name: ${{matrix.DB-name}}

      - name: Start IginX
        uses: ./.github/actions/iginxRunner

#      - name: Prepare CapExp environment
#        if: always()
#        uses: ./.github/actions/capacityExpansionUnionTest
#        with:
#          version: ${VERSION}
#          DB-name: ${{matrix.DB-name}}
#          Test-Way: oriNoDataExpNoData

      - name: Run InfluxDB
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi

      - name: TestControler IT
        if: always()
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/testUnion.sh"
          mvn test -q -Dtest=TestControler -DfailIfNoTests=false

  IoTDB-CE:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
        DB-name: [ "iotdb12" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Environmet Dependence
        uses: ./.github/actions/dependence
        with:
          python-version: ${{ matrix.python-version }}
          java: ${{ matrix.java }}
      - name: Run ZooKeeper
        uses: ./.github/actions/zookeeperRunner
      - name: Run IoTDB
        uses: ./.github/actions/iotdbRunner
        with:
          version: ${{matrix.DB-name}}

      - name: Change pom
        run: |
          mv test/pom.xml test/pom.xml.backup
          mv test/pom.xml.${{matrix.DB-name}} test/pom.xml
      - name: Install IginX with Maven
        shell: bash
        run: |
          mvn clean package -DskipTests
      #第 1 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: oriHasDataExpHasData
      #            mvn test -q -Dtest=IoTDBSqlScaleOutIT#oriHasDataExpHasDataIT -DfailIfNoTests=false
      #            mvn test -q -Dtest=IoTDBSessionScaleOutIT#oriHasDataExpHasDataIT -DfailIfNoTests=false
      #            mvn test -q -Dtest=IoTDBRestfulScaleOutIT#oriHasDataExpHasDataIT -DfailIfNoTests=false
      #            mvn test -q -Dtest=IoTDBTagScaleOutIT#oriHasDataExpHasDataIT -DfailIfNoTests=false
      - name: oriHasDataExpHasData IT
        if: always()
        run: |
          if [ "${{matrix.DB-name}}" == "iotdb12" ]; then
            mvn test -q -Dtest=IoTDB12HistoryDataCapacityExpansionIT#oriHasDataExpHasData, TagIT, RestIT, IoTDB12SessionIT, IoTDBSQLSessionIT -DfailIfNoTests=false
          else
            echo "${{matrix.DB-name}} is not supported"
          fi
      #第 2 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: oriNoDataExpNoData
      #            mvn test -q -Dtest=IoTDBSqlScaleOutIT#oriNoDataExpNoDataIT -DfailIfNoTests=false
      #            mvn test -q -Dtest=IoTDBSessionScaleOutIT#oriNoDataExpNoDataIT -DfailIfNoTests=false
      #            mvn test -q -Dtest=IoTDBRestfulScaleOutIT#oriNoDataExpNoDataIT -DfailIfNoTests=false
      #            mvn test -q -Dtest=IoTDBTagScaleOutIT#oriNoDataExpNoDataIT -DfailIfNoTests=false
      - name: oriNoDataExpNoData IT
        if: always()
        run: |
          if [ "${{matrix.DB-name}}" == "iotdb12" ]; then
            mvn test -q -Dtest=IoTDB12HistoryDataCapacityExpansionIT#oriNoDataExpNoData, TagIT, RestIT, IoTDB12SessionIT, IoTDBSQLSessionIT -DfailIfNoTests=false
          else
            echo "${{matrix.DB-name}} is not supported"
          fi
      #第 3 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: oriHasDataExpNoData
      #            mvn test -q -Dtest=IoTDBSqlScaleOutIT#oriHasDataExpNoDataIT -DfailIfNoTests=false
      #            mvn test -q -Dtest=IoTDBSessionScaleOutIT#oriHasDataExpNoDataIT -DfailIfNoTests=false
      #            mvn test -q -Dtest=IoTDBRestfulScaleOutIT#oriHasDataExpNoDataIT -DfailIfNoTests=false
      #            mvn test -q -Dtest=IoTDBTagScaleOutIT#oriHasDataExpNoDataIT -DfailIfNoTests=false
      - name: oriHasDataExpNoData IT
        if: always()
        run: |
          if [ "${{matrix.DB-name}}" == "iotdb12" ]; then
            mvn test -q -Dtest=IoTDB12HistoryDataCapacityExpansionIT#oriHasDataExpNoData, TagIT, RestIT, IoTDB12SessionIT, IoTDBSQLSessionIT -DfailIfNoTests=false
          else
            echo "${{matrix.DB-name}} is not supported"
          fi
      #第 4 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: oriNoDataExpHasData
#  mvn test -q -Dtest=IoTDBSqlScaleOutIT#oriNoDataExpHasDataIT -DfailIfNoTests=false
#  mvn test -q -Dtest=IoTDBSessionScaleOutIT#oriNoDataExpHasDataIT -DfailIfNoTests=false
#  mvn test -q -Dtest=IoTDBRestfulScaleOutIT#oriNoDataExpHasDataIT -DfailIfNoTests=false
#  mvn test -q -Dtest=IoTDBTagScaleOutIT#oriNoDataExpHasDataIT -DfailIfNoTests=false
#  mvn test -q -Dtest=IoTDB12HistoryDataCapacityExpansionIT#schemaPrefix -DfailIfNoTests=false
#  mvn test -q -Dtest=IoTDB12HistoryDataCapacityExpansionIT#testAddSameDataPrefixWithDiffSchemaPrefix_AND_testRemoveHistoryDataSource -DfailIfNoTests=false
      - name: oriNoDataExpHasData IT
        if: always()
        run: |
          if [ "${{matrix.DB-name}}" == "iotdb12" ]; then
            mvn test -q -Dtest=IoTDB12HistoryDataCapacityExpansionIT#oriNoDataExpHasData, TagIT, RestIT, IoTDB12SessionIT, IoTDBSQLSessionIT, IoTDB12HistoryDataCapacityExpansionIT#schemaPrefix, IoTDB12HistoryDataCapacityExpansionIT#testAddSameDataPrefixWithDiffSchemaPrefix_AND_testRemoveHistoryDataSource -DfailIfNoTests=false
          else
            echo "${{matrix.DB-name}} is not supported"
          fi
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

  DataPrefixWithMultiSchemaPrefix-InfluxDB-CE:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      #max-parallel: 20
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run ZooKeeper
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
            "${GITHUB_WORKSPACE}/.github/zk.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
            "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run InfluxDB
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_history_data_add.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_history_data_add.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_history_data_add_macos.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_history_data_add_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run IoTDB
        uses: ./.github/actions/iotdbRunner
        with:
          version: iotdb12
      - name: Change pom
        run: |
          mv test/pom.xml test/pom.xml.backup
          mv test/pom.xml.iotdb12 test/pom.xml
      - name: Install with Maven
        run: mvn clean package -DskipTests
      - name: Write history Data
        run: |
          mvn test -q -Dtest=InfluxDBHistoryDataGeneratorTest -DfailIfNoTests=false
          sleep 5
      - name: Start IginX
        run: |
          chmod +x "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh"
          nohup "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh" &

      - name: Add Same DataPrefix With DiffSchemaPrefix IT
        run: |
          mvn test -q -Dtest=InfluxDBHistoryDataCapacityExpansionIT#testAddSameDataPrefixWithDiffSchemaPrefix -DfailIfNoTests=false