name: "ITTest-ds-InfluxDB"

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
env:
  VERSION: 0.6.0-SNAPSHOT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  InfluxDB-Capacity-Expansion-ds:
    strategy:
      fail-fast: false
      #max-parallel: 20
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run ZooKeeper
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
            "${GITHUB_WORKSPACE}/.github/zk.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
            "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run InfluxDB and change default config
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_history_data.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_history_data.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_history_data_macos.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_history_data_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Install with Maven
        run: mvn clean package -DskipTests
      - name: Write history Data
        run: |
          mvn test -q -Dtest=InfluxDBHistoryDataGeneratorTest -DfailIfNoTests=false
          sleep 10
      - name: Start IginX
        run: |
          chmod +x "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh"
          nohup "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh" &