name: "ITTest-ds-InfluxDB"

on: workflow_dispatch
env:
  VERSION: 0.6.0-SNAPSHOT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  IGinX-Build:
    runs-on: ubuntu-latest
    matrix:
        java: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven Package
        run: mvn clean package -DskipTests
      - name: Upload Outputs and Intermediates
        uses: actions/upload-artifact@v3
        with:
          name: IGinX-Java${{ matrix.java }}-Dev
          path: .
  InfluxDB-Capacity-Expansion-ds:
    strategy:
      fail-fast: false
      #max-parallel: 20
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download IGinX-Java${{ matrix.java }}-Dev
        uses: actions/download-artifact@v3
        with:
          name: IGinX-Java${{ matrix.java }}-Dev
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
      - name: Run ZooKeeper
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
            "${GITHUB_WORKSPACE}/.github/zk.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
            "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run InfluxDB and change default config
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_history_data.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_history_data.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_history_data_macos.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_history_data_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Write history Data
        run: |
          mvn test -q -Dtest=InfluxDBHistoryDataGeneratorTest -DfailIfNoTests=false
          sleep 10
      - name: Start IginX
        run: |
          chmod +x "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh"
          nohup "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh" &

  InfluxDB-SQL-ds:
    strategy:
      fail-fast: false
      #max-parallel: 20
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download IGinX-Java${{ matrix.java }}-Dev
        uses: actions/download-artifact@v3
        with:
          name: IGinX-Java${{ matrix.java }}-Dev
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
      - name: Run ZooKeeper
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
            "${GITHUB_WORKSPACE}/.github/zk.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
            "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run InfluxDB
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Start IginX
        run: |
          chmod +x "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh"
          nohup "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh" &
      - name: A Lame Integration Test with Maven for SQL
        run: mvn surefire:test -q -Dtest=InfluxDBSQLSessionIT -DfailIfNoTests=false
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

  InfluxDB-SQL-SessionPool-ds:
    strategy:
      fail-fast: false
      #max-parallel: 20
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download IGinX-Java${{ matrix.java }}-Dev
        uses: actions/download-artifact@v3
        with:
          name: IGinX-Java${{ matrix.java }}-Dev
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
      - name: Run ZooKeeper
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
            "${GITHUB_WORKSPACE}/.github/zk.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
            "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run InfluxDB
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Start IginX
        uses: ./.github/actions/iginxRunner
        with:
          version: ${VERSION}

      - name: Change Config to Start IGinX_2
        uses: ./.github/actions/confWriter
        with:
          confFile: "iginxConf"

      - name: Start IginX_2
        uses: ./.github/actions/iginxRunner
        with:
          version: ${VERSION}
      - name: A Lame Integration Test with Maven for SQL
        run: mvn surefire:test -q -Dtest=InfluxDBSQLSessionPoolIT -DfailIfNoTests=false
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
