name: "Free-threading Python Test"

on:
    workflow_call:
        inputs:
            java-matrix:
                description: "The java version to run the test on"
                type: string
                required: false
                default: '["8"]'
            os-matrix:
                description: "The operating system to run the test on"
                type: string
                required: false
                default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            metadata-matrix:
                description: "The metadata to run the test on"
                type: string
                required: false
                default: '["zookeeper", "etcd"]'
            db-matrix:
                description: "The database to run the test on"
                type: string
                required: false
                default: '["IoTDB12", "FileSystem"]'

jobs:
    Free-threading-Python-Test:
        timeout-minutes: 40
        strategy:
            fail-fast: false
            matrix:
                java: ${{ fromJSON(inputs.java-matrix) }}
                os: ${{ fromJSON(inputs.os-matrix) }}
                metadata: ${{ fromJSON(inputs.metadata-matrix) }}
                DB-name: ${{ fromJSON(inputs.db-matrix) }}
        runs-on: ${{ matrix.os }}
        env:
          # only used in this workflow file
          IGINX_CONDA_ENV: "iginxEnv"
        steps:
            - uses: actions/checkout@v4
              # use free-threading python instead of stable version
            - name: Environment dependence
              uses: ./.github/actions/dependence
              with:
                  java: ${{ matrix.java }}
                  free-thread-python-required: "true"
                  scope: "only-java"
                  iginx-conda-flag: "true"
                  iginx-conda-env: ${{ env.IGINX_CONDA_ENV }}

            - name: Run Metadata
              uses: ./.github/actions/metadataRunner
              with:
                  metadata: ${{ matrix.metadata }}

            - name: Run DB
              uses: ./.github/actions/dbRunner
              with:
                  DB-name: ${{ matrix.DB-name }}

            - name: Install IGinX with Maven
              shell: bash
              run: |
                  mvn clean package -DskipTests -P-format -q

            - name: Change IGinX config
              uses: ./.github/actions/confWriter
              with:
                  DB-name: ${{ matrix.DB-name }}
                  Set-Filter-Fragment-OFF: "true"
                  Metadata: ${{ matrix.metadata }}
                  use-free-thread-python: "true"

            - name: Start IGinX
              uses: ./.github/actions/iginxRunner
              with:
                activate-conda-flag: "true"
                iginx-conda-env:  ${{ env.IGINX_CONDA_ENV }}

            - name: TestController IT
              if: always()
              shell: bash -el {0}
              env:
                  METADATA_STORAGE: ${{ matrix.metadata }}
              run: |
                  conda activate ${{ env.IGINX_CONDA_ENV }}
                  chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/test_union.sh"
                  mvn test -q -Dtest=Controller -DfailIfNoTests=false -P-format

            - name: Show IGinX log
              if: always()
              shell: bash
              run: |
                  cat iginx-*.log
