name: Full Test Suite

on:
    schedule:
        - cron: "0 0 * * 0" # every Sunday
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    unit-test:
        uses: ./.github/workflows/unit-test.yml
    unit-mds:
        uses: ./.github/workflows/unit-mds.yml
    case-regression:
        uses: ./.github/workflows/case-regression.yml
    standalone-test:
        uses: ./.github/workflows/standalone-test.yml
    standalone-test-pushdown:
        uses: ./.github/workflows/standalone-test-pushdown.yml
    db-ce:
        uses: ./.github/workflows/DB-CE.yml
    remote-test:
        uses: ./.github/workflows/remote-test.yml
