name: "ITTest-ds-InfluxDB"

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
env:
  VERSION: 0.6.0-SNAPSHOT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  InfluxDB-SQL-ds:
    strategy:
      fail-fast: false
      #max-parallel: 20
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run ZooKeeper
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
            "${GITHUB_WORKSPACE}/.github/zk.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
            "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run InfluxDB
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Install with Maven
        run: mvn clean package -DskipTests
      - name: Start IginX
        run: |
          chmod +x "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh"
          nohup "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh" &
      - name: A Lame Integration Test with Maven for SQL
        run: mvn test -q -Dtest=InfluxDBSQLSessionIT -DfailIfNoTests=false
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

  InfluxDB-SQL-SessionPool-ds:
    strategy:
      fail-fast: false
      #max-parallel: 20
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run ZooKeeper
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
            "${GITHUB_WORKSPACE}/.github/zk.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
            "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run InfluxDB
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Install with Maven
        run: mvn clean package -DskipTests
      - name: Start IginX
        uses: ./.github/actions/iginxRunner
        with:
          version: ${VERSION}

      - name: Change Config to Start IGinX_2
        uses: ./.github/actions/confWriter
        with:
          confFile: "iginxConf"

      - name: Start IginX_2
        uses: ./.github/actions/iginxRunner
        with:
          version: ${VERSION}
      - name: A Lame Integration Test with Maven for SQL
        run: mvn test -q -Dtest=InfluxDBSQLSessionPoolIT -DfailIfNoTests=false
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

  DataPrefixWithMultiSchemaPrefix-InfluxDB-CE:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      #max-parallel: 20
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run ZooKeeper
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
            "${GITHUB_WORKSPACE}/.github/zk.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
            "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run InfluxDB
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_history_data_add.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_history_data_add.sh"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x "${GITHUB_WORKSPACE}/.github/influxdb_history_data_add_macos.sh"
            "${GITHUB_WORKSPACE}/.github/influxdb_history_data_add_macos.sh"
          else
            echo "$RUNNER_OS is not supported"
            exit 1
          fi
      - name: Run IoTDB
        uses: ./.github/actions/dbRunner
        with:
          version: iotdb12
      - name: Change pom
        run: |
          mv test/pom.xml test/pom.xml.backup
          mv test/pom.xml.iotdb12 test/pom.xml
      - name: Install with Maven
        run: mvn clean package -DskipTests
      - name: Write history Data
        run: |
          mvn test -q -Dtest=InfluxDBHistoryDataGeneratorTest -DfailIfNoTests=false
          sleep 5
      - name: Start IginX
        run: |
          chmod +x "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh"
          nohup "${GITHUB_WORKSPACE}/core/target/iginx-core-${VERSION}/sbin/start_iginx.sh" &

      - name: Add Same DataPrefix With DiffSchemaPrefix IT
        run: |
          mvn test -q -Dtest=InfluxDBHistoryDataCapacityExpansionIT#testAddSameDataPrefixWithDiffSchemaPrefix -DfailIfNoTests=false