name: lints

on:
    pull_request:

permissions:
    pull-requests: read

jobs:
    formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 # v2 minimum required
            - name: Check format with Maven
              shell: bash
              run: |
                  mvn clean spotless:check
    license:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 # v2 minimum required
            - name: Check license headers
              shell: bash
              run: |
                  mvn clean license:check
    py-session:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: 8
                  distribution: temurin
                  cache: maven
            - name: remove py-session thrift
              working-directory: session_py
              run: rm -rf iginx/iginx_pyclient/thrift
            - name: generate py-session thrift
              run: mvn clean compile -pl thrift,session_py -DskipTests
            - name: check py-session difference
              working-directory: session_py
              run: git diff --minimal --exit-code

    pull-request-name:
        name: Validate PR title
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    analyze-required-check:
        if: always()
        needs: # List of jobs that must pass. Add more jobs if needed.
            - formatting
            - license
            - py-session
            - pull-request-name
        runs-on: ubuntu-latest
        steps:
            - name: Decide whether the needed jobs succeeded or failed
              uses: re-actors/alls-green@release/v1
              with:
                  jobs: ${{ toJSON(needs) }}
