name: PolyStore Benchmark Tests

on:
    push:
        branches: [feat-benchmark]

env:
    VERSION: 0.6.0-SNAPSHOT
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  PolyStore-Benchmark-Test:
        timeout-minutes: 35
        strategy:
            fail-fast: false
            matrix:
                java: [8]
                python-version: ["3.9"]
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
          - uses: actions/checkout@v2
          - name: Environment dependence
            uses: ./.github/actions/dependence
            with:
              python-version: ${{ matrix.python-version }}
              java: ${{ matrix.java }}

          - name: Run ZooKeeper
            uses: ./.github/actions/zookeeperRunner

          - name: Run DB
            uses: ./.github/actions/dbRunner
            with:
              DB-name: "IoTDB12"

          - name: Run PostgreSQL
            shell: bash
            run: |
              chmod +x "${GITHUB_WORKSPACE}/.github/scripts/benchmarks/postgres.sh"
              "${GITHUB_WORKSPACE}/.github/scripts/benchmarks/postgres.sh"

          - name: Run MongoDB
            shell: bash
            run: |
              chmod +x "${GITHUB_WORKSPACE}/.github/scripts/benchmarks/mongodb.sh"
              "${GITHUB_WORKSPACE}/.github/scripts/benchmarks/mongodb.sh"

          - name: Install IGinX with Maven
            shell: bash
            run: |
              mvn clean package -DskipTests -P-format -q

          - name: Change IGinX config
            uses: ./.github/actions/confWriter
            with:
              DB-name: "IoTDB12"
              Set-Filter-Fragment-OFF: "true"

          # start udf path test first to avoid being effected
          - name: Start IGinX
            uses: ./.github/actions/iginxRunner
            with:
              version: ${VERSION}
              if-test-udf: "true"

          - name: set client test context
            uses: ./.github/actions/context
            with:
              work-name: restart-iginx-zk

          - name: set client test context
            uses: ./.github/actions/context
            with:
              DB-name: "IoTDB12"
              shell: client-before

          - name: Start data cleaning
            shell: bash
            run: |
              chmod +x "${GITHUB_WORKSPACE}/.github/scripts/benchmarks/dataCleaning.sh"
              "${GITHUB_WORKSPACE}/.github/scripts/benchmarks/dataCleaning.sh"

