name: "Remote Service Test"
on:
    pull_request:
        types: [opened, reopened]
        branches:
            - main
env:
    VERSION: 0.6.0-SNAPSHOT
    FUNCTEST: RemoteUDFIT
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Union-DB-Test:
        timeout-minutes: 30
        strategy:
            fail-fast: false
            matrix:
                java: [8]
                python-version: ["3.9"]
                os: [macos-13]
                #                os: [ubuntu-latest, macos-13, windows-latest]
                DB-name:
                    [
                        "IoTDB12",
                        "InfluxDB",
                        "Parquet",
                        "PostgreSQL",
                        "FileSystem",
                        "Redis",
                        "MongoDB",
                    ]
                metadata: [zookeeper]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Environment dependence
              uses: ./.github/actions/dependence
              with:
                  python-version: ${{ matrix.python-version }}
                  java: ${{ matrix.java }}

            - if: runner.os == 'Windows'
              name: Set up Docker Firewall on Windows
              run: |
                  $feature = Install-WindowsFeature -Name Containers
                  if ($feature.RestartNeeded -eq 'Yes') {
                    Restart-Computer -Force
                    Start-Sleep -s 60
                  }
                  Get-NetFirewallProfile
                  Set-NetFirewallProfile -Profile Public -Enabled False
                  echo "############################"
                  New-NetFirewallRule -DisplayName "Allow ICMPv4-In" -Protocol ICMPv4 -IcmpType 8 -Action Allow -Direction Inbound
                  New-NetFirewallRule -DisplayName "Allow ICMPv4-Out" -Protocol ICMPv4 -IcmpType 8 -Action Allow -Direction Outbound

            - if: runner.os == 'Windows'
              name: Build & Run Client image
              shell: cmd
              run: |
                  mvn clean package -q -pl client -am -Dmaven.test.skip=true -P-format -e && cd %GITHUB_WORKSPACE%\docker\client && build-no-maven.bat && run_docker.bat

            - name: Run Metadata
              uses: ./.github/actions/metadataRunner
              with:
                  metadata: ${{ matrix.metadata }}

            - name: Run DB
              uses: ./.github/actions/dbRunner
              with:
                  DB-name: ${{ matrix.DB-name }}

            - name: Install IGinX with Maven
              shell: bash
              run: |
                  mvn clean package -DskipTests -P-format -q

            - if: runner.os != 'Windows'
              name: Build & Run Client image
              shell: bash
              run: |
                  cd ${GITHUB_WORKSPACE}/docker/client && \
                  chmod +x "build-no-maven.sh" && \
                  chmod +x "run_docker.sh" && \
                  "./build-no-maven.sh" && \
                  "./run_docker.sh"

            - name: Change IGinX config
              uses: ./.github/actions/confWriter
              with:
                  DB-name: ${{ matrix.DB-name }}
                  Set-Filter-Fragment-OFF: "true"
                  Metadata: ${{ matrix.metadata }}
            #                Switch-DB: "true"

            - name: Start IGinX
              uses: ./.github/actions/iginxRunner
              with:
                  version: ${VERSION}

            - name: Register Remote UDFs
              shell: bash
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                    chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf.sh"
                    "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf.sh" ${{ matrix.os }}
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                    chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf_macos.sh"
                    "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf_macos.sh"
                  else
                    chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf_windows.sh"
                    "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf_windows.sh"
                  fi

            - name: Run Tests
              shell: bash
              run: |
                  mvn test -q -Dtest=${FUNCTEST} -DfailIfNoTests=false -P-format

            - name: Show IGinX log
              if: always()
              shell: bash
              run: |
                  cat iginx-*.log
