name: "Remote Service Test"
on:
    pull_request:
        types: [opened, reopened]
        branches:
            - main
env:
    VERSION: 0.6.0-SNAPSHOT
    FUNCTEST: RemoteUDFIT
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Union-DB-Test:
        timeout-minutes: 30
        strategy:
            fail-fast: false
            matrix:
                java: [8]
                python-version: ["3.9"]
                os: [windows-latest]
                DB-name:
                    [
                        "Parquet"
                    ]
                metadata: [zookeeper]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Environment dependence
              uses: ./.github/actions/dependence
              with:
                  python-version: ${{ matrix.python-version }}
                  java: ${{ matrix.java }}

            - name: Set up Docker
              run: |
                $feature = Install-WindowsFeature -Name Containers
                if ($feature.RestartNeeded -eq 'Yes') {
                  Restart-Computer -Force
                  Start-Sleep -s 60
                }
                Get-NetFirewallProfile
                Set-NetFirewallProfile -Profile Public -Enabled False
                echo "############################"
                Get-NetFirewallRule
                New-NetFirewallRule -DisplayName "Allow ICMPv4-In" -Protocol ICMPv4 -IcmpType 8 -Action Allow -Direction Inbound
                New-NetFirewallRule -DisplayName "Allow ICMPv4-Out" -Protocol ICMPv4 -IcmpType 8 -Action Allow -Direction Outbound

            - if: runner.os == 'Windows'
              name: Create Docker Network
              shell: cmd
              run: |
                ipconfig
                docker --version
                docker network ls
                docker network create -d nat --attachable --subnet 172.40.0.0/16 docker-cluster-iginx
                docker network create -d transparent TransNet

            - name: Run Docker container and test network
              run: |
                docker run --name=test-container -d mcr.microsoft.com/windows/servercore:ltsc2022 ping 8.8.8.8
                Start-Sleep -s 10
                docker logs test-container

            - name: Clean up
              run: |
                docker stop test-container
                docker rm test-container



            - if: runner.os == 'Windows'
              name: Build & Run Client image
              shell: cmd
              run: |
                mvn clean package -q -pl client -am -Dmaven.test.skip=true -P-format && cd %GITHUB_WORKSPACE%\docker\client && build.bat && run_docker.bat

            - name: Run Metadata
              uses: ./.github/actions/metadataRunner
              with:
                metadata: ${{ matrix.metadata }}

            - name: Run DB
              uses: ./.github/actions/dbRunner
              with:
                DB-name: ${{ matrix.DB-name }}

            - name: Install IGinX with Maven
              shell: bash
              run: |
                  mvn clean package -DskipTests -P-format -q

            - if: runner.os != 'Windows'
              name: Create Docker Network
              shell: bash
              run: |
                docker --version
                docker network create -d bridge --attachable --subnet 172.40.0.0/16 docker-cluster-iginx

            - if: runner.os != 'Windows'
              name: Build & Run Client image
              shell: bash
              run: |
                  cd ${GITHUB_WORKSPACE}/docker/client && \
                  chmod +x "build.sh" && \
                  chmod +x "run_docker.sh" && \
                  "./build.sh" && \
                  "./run_docker.sh"

            - name: Change IGinX config
              uses: ./.github/actions/confWriter
              with:
                DB-name: ${{ matrix.DB-name }}
                Set-Filter-Fragment-OFF: "true"
                Metadata: ${{ matrix.metadata }}
                Switch-DB: "true"

            - name: Start IGinX
              uses: ./.github/actions/iginxRunner
              with:
                version: ${VERSION}

            - if: runner.os == 'Windows'
              name: Register Remote UDFs
              shell: bash
              run: |
                  chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf_windows.sh"
                  "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf_windows.sh" ${{ matrix.os }}

            - if: runner.os != 'Windows'
              name: Register Remote UDFs
              shell: bash
              run: |
                chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf.sh"
                "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf.sh" ${{ matrix.os }}

            - name: Run Tests
              shell: bash
              run: |
                  mvn test -q -Dtest=${FUNCTEST} -DfailIfNoTests=false -P-format

            - name: Show IGinX log
              if: always()
              shell: bash
              run: |
                  cat iginx-*.log
