name: "Remote Service Test"
on:
    pull_request:
        types: [opened, reopened]
        branches:
            - main
env:
    VERSION: 0.6.0-SNAPSHOT
    FUNCTEST: RemoteUDFIT
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Union-DB-Test:
        timeout-minutes: 30
        strategy:
            fail-fast: false
            matrix:
                java: [8]
                python-version: ["3.9"]
                os: [ubuntu-latest, macos-12, windows-latest]
                DB-name:
                    [
                        "IoTDB12",
                        "InfluxDB",
                        "Parquet",
                        "PostgreSQL",
                        "FileSystem",
                        "Redis",
                        "MongoDB",
                    ]
                metadata: [zookeeper]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Environment dependence
              uses: ./.github/actions/dependence
              with:
                  python-version: ${{ matrix.python-version }}
                  java: ${{ matrix.java }}

            - name: Install IGinX with Maven
              shell: bash
              run: |
                  mvn clean package -DskipTests -P-format -q

            - if: runner.os == 'Windows'
              name: Create Docker Network
              shell: cmd
              run: |
                docker --version
                docker network create -d nat --attachable --subnet 172.40.0.0/16 docker-cluster-iginx

            - if: runner.os != 'Windows'
              name: Create Docker Network
              shell: bash
              run: |
                docker --version
                docker network create -d bridge --attachable --subnet 172.40.0.0/16 docker-cluster-iginx

            - name: Change IGinX config
              uses: ./.github/actions/confWriter
              with:
                  DB-name: ${{ matrix.DB-name }}
                  Set-Filter-Fragment-OFF: "true"
                  Metadata: ${{ matrix.metadata }}
                  Switch-DB: "true"

            - if: runner.os == 'Windows'
              name: Build & Run Client image
              shell: cmd
              run: |
                  cd %GITHUB_WORKSPACE%\docker\client && build.bat && run_docker.bat

            - if: runner.os != 'Windows'
              name: Build & Run Client image
              shell: bash
              run: |
                  cd ${GITHUB_WORKSPACE}/docker/client && \
                  chmod +x "build.sh" && \
                  chmod +x "run_docker.sh" && \
                  "./build.sh" && \
                  "./run_docker.sh"

            - name: Run Metadata
              uses: ./.github/actions/metadataRunner
              with:
                metadata: ${{ matrix.metadata }}

            - name: Run DB
              uses: ./.github/actions/dbRunner
              with:
                DB-name: ${{ matrix.DB-name }}

            - name: Start IGinX
              uses: ./.github/actions/iginxRunner
              with:
                version: ${VERSION}

            - name: Register Remote UDFs
              shell: bash
              run: |
                  chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf.sh"
                  "${GITHUB_WORKSPACE}/.github/scripts/test/cli/test_remote_udf.sh"

            - name: Run Tests
              shell: bash
              run: |
                  mvn test -q -Dtest=${FUNCTEST} -DfailIfNoTests=false -P-format

            - name: Show IGinX log
              if: always()
              shell: bash
              run: |
                  cat iginx-*.log
