name: Standard Test Suite

on:
    pull_request: # when a PR is opened or reopened
        types: [opened, reopened]
        branches:
            - main

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    unit-test:
        uses: ./.github/workflows/unit-test.yml
    unit-mds:
        uses: ./.github/workflows/test-metadata.yml
    case-regression:
        uses: ./.github/workflows/test-mixed-cluster.yml
        with:
            metadata-matrix: '["zookeeper"]'
    standalone-test:
        uses: ./.github/workflows/test-cli.yml
        with:
            push-down: false
            metadata-matrix: '["zookeeper"]'
    standalone-test-pushdown:
        uses: ./.github/workflows/test-single-database.yml
        with:
            push-down: true
            metadata-matrix: '["zookeeper"]'
    optimizer-test:
        uses: ./.github/workflows/test-optimizer.yml
        with:
            metadata-matrix: '["zookeeper"]'
    client-test:
        uses: ./.github/workflows/test-cli.yml
        with:
            metadata-matrix: '["zookeeper"]'
    db-ce:
        uses: ./.github/workflows/test-capacity-expansion.yml
        with:
            metadata-matrix: '["zookeeper"]'
    remote-test:
        uses: ./.github/workflows/test-remote.yml
        with:
            metadata-matrix: '["zookeeper"]'
    assemebly-test:
        uses: ./.github/workflows/test-assembly.yml
    tpc-h-regression-test:
        uses: ./.github/workflows/tpc-h.yml
        with:
            os-matrix: '["ubuntu-latest"]'
            metadata-matrix: '["zookeeper"]'
