name: "UDF-Path-Detection-Test"

on:
    pull_request:
        types: [opened, reopened]
        branches:
            - main

env:
    VERSION: 0.6.0-SNAPSHOT

jobs:
    UDF-Path-Test:
        strategy:
            matrix:
                java: [8]
                python-version: ["3.7.16"]
                os: [ubuntu-latest, macos-latest]
                DB-name: ["IoTDB12"]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Environment dependence
              uses: ./.github/actions/dependence
              with:
                  python-version: ${{ matrix.python-version }}
                  java: ${{ matrix.java }}

            - name: Run ZooKeeper
              uses: ./.github/actions/zookeeperRunner

            - name: Run DB
              uses: ./.github/actions/dbRunner
              with:
                  DB-name: ${{ matrix.DB-name }}

            - name: Install IGinX with Maven
              shell: bash
              run: |
                  mvn clean package -DskipTests -P-format -q

            - name: Start IGinX
              uses: ./.github/actions/iginxRunner
              with:
                  version: ${VERSION}
                  if-test-udf: "true"
