name: Upload Binaries to Github

on:
    release:
        types: [published]

jobs:
    upload-package:
        name: Upload Package to Github Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: "8"
                  distribution: "temurin"
                  cache: "maven"
            - name: package
              run: mvn --batch-mode -DskipTests=true package -P release,!format
            - name: upload
              uses: svenstaro/upload-release-action@v2
              with:
                  file: "**/*.tar.gz"
                  file_glob: true
                  overwrite: true
    upload-deploy:
        name: Upload Maven Repository to Github Pages
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: "8"
                  distribution: "temurin"
                  cache: "maven"
            - name: checkout pages branch
              uses: actions/checkout@v4
              with:
                  path: pages
                  ref: pages
                  fetch-depth: 0
            - name: deploy
              run: mvn --batch-mode -DskipTests=true -Ddeploy.repo.dir=$(pwd)/pages deploy -P !format
            - name: create pull request
              uses: peter-evans/create-pull-request@v6
              with:
                  path: pages
                  add-paths: |
                      maven-repo
                      maven-snapshot-repo
                  branch: release-bot/pages
                  commit-message: "chore(repo): update maven repository"
                  title: "chore(repo): update maven repository"
