name: Upload Binaries to Github Release

on:
    release:
        types: [created]

jobs:
    upload-binary:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: "8"
                  distribution: "temurin"
                  cache: "maven"
            - name: package
              run: mvn --batch-mode -DskipTests=true package -P release,!format
            - name: upload
              uses: svenstaro/upload-release-action@v2
              with:
                  file: "**/*.tar.gz"
                  file_glob: true
                  overwrite: true
